use pi_session_manager::subagent::parse_meta_json;
/// @tintinweb/pi-subagents Compatibility Test
/// Validate that we can parse meta.json files generated by @tintinweb/pi-subagents
use pi_session_manager::SubagentRunInfo;

#[test]
fn test_tintinweb_meta_json_format() {
    // Sample meta.json from @tintinweb/pi-subagents
    let json = r#"{
        "runId": "abc123def456",
        "agent": "Explore",
        "model": "anthropic/claude-sonnet-4",
        "exitCode": 0,
        "usage": {
            "input": 1234,
            "output": 5678,
            "cacheRead": 0,
            "cacheWrite": 0,
            "cost": 0.015,
            "turns": 5
        },
        "durationMs": 4500,
        "toolCount": 3,
        "timestamp": 1711450800000
    }"#;

    let info = parse_meta_json(json).expect("Should parse @tintinweb format");

    // Verify all fields are correctly parsed
    assert_eq!(info.run_id, "abc123def456");
    assert_eq!(info.agent, "Explore");
    assert_eq!(info.model, "anthropic/claude-sonnet-4");
    assert_eq!(info.exit_code, 0);
    assert!((info.cost - 0.015).abs() < 1e-9);
    assert_eq!(info.input_tokens, 1234);
    assert_eq!(info.output_tokens, 5678);
    assert_eq!(info.cache_read_tokens, 0);
    assert_eq!(info.cache_write_tokens, 0);
    assert_eq!(info.duration_ms, 4500);
    assert_eq!(info.tool_count, 3);
    assert_eq!(info.timestamp, 1711450800000);
    assert_eq!(info.turns, 5); // Critical for @tintinweb compatibility

    println!("✅ @tintinweb/pi-subagents meta.json format test passed");
}

#[test]
fn test_tintinweb_meta_json_with_high_turns() {
    // Test with higher turn count to ensure turns field works correctly
    let json = r#"{
        "runId": "long-run-789",
        "agent": "worker",
        "model": "anthropic/claude-opus-4-6",
        "exitCode": 0,
        "usage": {
            "input": 50000,
            "output": 30000,
            "cacheRead": 100000,
            "cacheWrite": 50000,
            "cost": 2.50,
            "turns": 50
        },
        "durationMs": 120000,
        "toolCount": 75,
        "timestamp": 1711537200000
    }"#;

    let info = parse_meta_json(json).expect("Should parse high-turn session");
    assert_eq!(info.turns, 50);
    assert_eq!(info.tool_count, 75);
    assert!((info.cost - 2.50).abs() < 1e-9);

    println!(
        "✅ High turn count test passed (turns={}, tools={})",
        info.turns, info.tool_count
    );
}

#[test]
fn test_tintinweb_meta_json_missing_turns_defaults_to_zero() {
    // Test backward compatibility: turns field missing should default to 0
    let json = r#"{
        "runId": "old-format-123",
        "agent": "scout",
        "model": "haiku",
        "exitCode": 0,
        "usage": {
            "input": 500,
            "output": 300,
            "cacheRead": 0,
            "cacheWrite": 0,
            "cost": 0.002
        },
        "durationMs": 1000,
        "toolCount": 2,
        "timestamp": 1711364400000
    }"#;

    let info = parse_meta_json(json).expect("Should parse old format without turns");
    assert_eq!(info.turns, 0); // Should default to 0

    println!("✅ Backward compatibility test passed (turns defaults to 0)");
}

#[test]
fn test_tintinweb_meta_json_aborted_session() {
    // Test aborted session (exitCode != 0)
    let json = r#"{
        "runId": "aborted-456",
        "agent": "Plan",
        "model": "anthropic/claude-sonnet-4",
        "exitCode": 1,
        "usage": {
            "input": 2000,
            "output": 1000,
            "cacheRead": 0,
            "cacheWrite": 0,
            "cost": 0.008,
            "turns": 3
        },
        "durationMs": 2000,
        "toolCount": 2,
        "timestamp": 1711623600000
    }"#;

    let info = parse_meta_json(json).expect("Should parse aborted session");
    assert_eq!(info.exit_code, 1);
    assert_eq!(info.turns, 3);

    println!(
        "✅ Aborted session test passed (exitCode={}, turns={})",
        info.exit_code, info.turns
    );
}
