import type { FavoriteItem, SessionTag, Tag } from '../types'

export interface DemoTokenUsageSeed {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

export interface DemoSubagentSeed {
  runs: number
  tokens: number
  cost: number
  model: string
  agent: string
}

export interface DemoSessionSeed {
  id: string
  path: string
  cwd: string
  name: string
  created: string
  modified: string
  messageCount: number
  firstMessage: string
  lastMessage: string
  assistantSummary: string
  model: string
  provider: string
  toolName: string
  toolArgs: Record<string, unknown>
  toolOutput: string
  keywords: string[]
  tokenUsage: DemoTokenUsageSeed
  includeCompaction?: boolean
  includeBranchSummary?: boolean
  includeCustomMessage?: boolean
  includeToolError?: boolean
  subagent?: DemoSubagentSeed
}

export const TOKEN_RATES: Record<string, { input: number; output: number }> = {
  'gpt-4o': { input: 5, output: 15 },
  'gpt-4o-mini': { input: 0.15, output: 0.6 },
  'claude-3-5-sonnet': { input: 3, output: 15 },
  'claude-3-haiku': { input: 0.25, output: 1.25 },
  default: { input: 1, output: 2 },
}

export const DEMO_SESSION_SEEDS: DemoSessionSeed[] = [
  {
    id: 'demo-001',
    path: '/demo/commerce/session-001.jsonl',
    cwd: '/Users/demo/commerce-platform',
    name: 'Checkout 风险规则联调',
    created: '2026-02-03T09:10:00Z',
    modified: '2026-02-03T11:42:00Z',
    messageCount: 34,
    firstMessage: '支付成功率掉到 91%，帮我定位 checkout 风险规则误杀。',
    lastMessage: '已下发灰度策略，风险误杀从 8.7% 降到 1.4%。',
    assistantSummary: '定位到规则顺序冲突并给出灰度回滚方案。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'query_metrics',
    toolArgs: { dashboard: 'checkout', window: '24h' },
    toolOutput: '高风险规则 v3 在 iOS 渠道触发率异常升高，峰值 31.2%。',
    keywords: ['checkout', 'risk', '灰度', '支付', '误杀'],
    tokenUsage: { input: 28500, output: 11200, cacheRead: 2400, cacheWrite: 800 },
    includeBranchSummary: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-002',
    path: '/demo/commerce/session-002.jsonl',
    cwd: '/Users/demo/commerce-platform',
    name: '库存扣减并发修复',
    created: '2026-02-04T07:45:00Z',
    modified: '2026-02-04T10:20:00Z',
    messageCount: 27,
    firstMessage: '秒杀库存出现负数，需要一个低侵入修复方案。',
    lastMessage: '引入乐观锁 + 重试后，库存一致性恢复且 p95 延迟仅 +4ms。',
    assistantSummary: '使用行版本号和失败重试修复并发超卖。',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'explain_sql_plan',
    toolArgs: { table: 'inventory', statement: 'update ... where version = ?' },
    toolOutput: '执行计划显示主键命中，冲突主要来自热点 SKU 行锁竞争。',
    keywords: ['inventory', '并发', '秒杀', '乐观锁', 'retry'],
    tokenUsage: { input: 21400, output: 9800, cacheRead: 1800, cacheWrite: 620 },
    includeCompaction: true,
  },
  {
    id: 'demo-003',
    path: '/demo/analytics/session-003.jsonl',
    cwd: '/Users/demo/analytics-suite',
    name: '指标看板慢查询治理',
    created: '2026-02-06T05:20:00Z',
    modified: '2026-02-06T09:12:00Z',
    messageCount: 31,
    firstMessage: 'BI 看板首屏要 18 秒，帮我做查询分层优化。',
    lastMessage: '冷热数据分层后首屏降到 2.8 秒，CPU 峰值下降 37%。',
    assistantSummary: '通过预聚合和冷热分层显著降低响应时间。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'profile_query',
    toolArgs: { queryId: 'bi_home_top_cards' },
    toolOutput: '主要耗时在跨月聚合与 JSON 字段函数过滤。',
    keywords: ['dashboard', 'slow query', 'pre-aggregation', 'BI'],
    tokenUsage: { input: 30100, output: 14500, cacheRead: 2600, cacheWrite: 950 },
    includeBranchSummary: true,
  },
  {
    id: 'demo-004',
    path: '/demo/mobile/session-004.jsonl',
    cwd: '/Users/demo/mobile-superapp',
    name: 'React Native 包体积瘦身',
    created: '2026-02-08T03:35:00Z',
    modified: '2026-02-08T06:48:00Z',
    messageCount: 19,
    firstMessage: 'Android 包从 64MB 涨到 96MB，需要一周内回到 70MB 内。',
    lastMessage: '移除冗余依赖并拆分资源后，release 包体积降至 68MB。',
    assistantSummary: '通过依赖裁剪和资源分包完成体积优化。',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'analyze_bundle',
    toolArgs: { platform: 'android', variant: 'release' },
    toolOutput: '三方图像库重复打包 + 本地化资源未按语言拆分。',
    keywords: ['React Native', 'bundle', 'Android', 'size'],
    tokenUsage: { input: 9800, output: 4200, cacheRead: 900, cacheWrite: 210 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-005',
    path: '/demo/infra/session-005.jsonl',
    cwd: '/Users/demo/infra-ops',
    name: 'K8s 节点抖动排障',
    created: '2026-02-10T01:10:00Z',
    modified: '2026-02-10T05:30:00Z',
    messageCount: 36,
    firstMessage: '凌晨节点频繁 NotReady，影响了 3 个核心服务。',
    lastMessage: '根因是 CNI 升级脚本竞态，已加锁并补齐回滚。',
    assistantSummary: '复盘节点抖动并完成发布流水线防护。',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'kubectl_events',
    toolArgs: { namespace: 'core', since: '6h' },
    toolOutput: '节点网络插件重启窗口与业务滚动发布重叠，触发探针雪崩。',
    keywords: ['k8s', 'node', 'NotReady', 'CNI', 'incident'],
    tokenUsage: { input: 32400, output: 16900, cacheRead: 3000, cacheWrite: 1100 },
    includeCompaction: true,
    includeBranchSummary: true,
  },
  {
    id: 'demo-006',
    path: '/demo/ai/session-006.jsonl',
    cwd: '/Users/demo/ai-assistant',
    name: 'RAG 召回质量回归',
    created: '2026-02-12T08:30:00Z',
    modified: '2026-02-12T12:05:00Z',
    messageCount: 29,
    firstMessage: '上线新 embedding 后，FAQ 命中率从 86% 掉到 63%。',
    lastMessage: '调整 chunk 策略与 rerank 后，命中率回升到 88.5%。',
    assistantSummary: '通过切分策略和重排参数恢复召回质量。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'compare_retrieval_runs',
    toolArgs: { baseline: 'embed-v2', candidate: 'embed-v3' },
    toolOutput: 'v3 在短问题场景过度依赖语义邻近，长文档召回下降明显。',
    keywords: ['RAG', 'embedding', 'rerank', 'recall'],
    tokenUsage: { input: 26700, output: 12800, cacheRead: 2200, cacheWrite: 760 },
    includeBranchSummary: true,
    subagent: {
      runs: 3,
      tokens: 18600,
      cost: 0.42,
      model: 'gpt-4o-mini',
      agent: 'retrieval-auditor',
    },
  },
  {
    id: 'demo-007',
    path: '/demo/analytics/session-007.jsonl',
    cwd: '/Users/demo/analytics-suite',
    name: 'SSE 推送丢消息修复',
    created: '2026-02-14T11:00:00Z',
    modified: '2026-02-14T12:55:00Z',
    messageCount: 17,
    firstMessage: '实时告警面板偶现空洞，怀疑 SSE reconnect 丢了增量。',
    lastMessage: '重连补偿窗口改为 Last-Event-ID + replay，空洞问题消失。',
    assistantSummary: '补齐断线重连期间的增量回放机制。',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'inspect_event_stream',
    toolArgs: { stream: 'alerts', sampleSeconds: 120 },
    toolOutput: '断线 2-4 秒内事件写入成功但前端缺补偿逻辑。',
    keywords: ['SSE', 'reconnect', 'alerts', 'replay'],
    tokenUsage: { input: 8600, output: 3900, cacheRead: 780, cacheWrite: 190 },
    includeToolError: true,
  },
  {
    id: 'demo-008',
    path: '/demo/commerce/session-008.jsonl',
    cwd: '/Users/demo/commerce-platform',
    name: '优惠券规则引擎重构',
    created: '2026-02-16T04:20:00Z',
    modified: '2026-02-16T08:15:00Z',
    messageCount: 33,
    firstMessage: '优惠叠加规则太混乱，活动期间经常打错折扣。',
    lastMessage: '新规则 DSL 上线后，回归样例通过率从 71% 提升到 99%。',
    assistantSummary: '将条件树抽象为 DSL 并补充规则测试矩阵。',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'generate_rule_matrix',
    toolArgs: { scenarios: 120, channels: ['app', 'h5', 'mini'] },
    toolOutput: '发现 23 组冲突规则，主要集中在满减与券包优先级。',
    keywords: ['coupon', 'DSL', 'rules engine', 'discount'],
    tokenUsage: { input: 29600, output: 14200, cacheRead: 2500, cacheWrite: 870 },
    includeCompaction: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-009',
    path: '/demo/mobile/session-009.jsonl',
    cwd: '/Users/demo/mobile-superapp',
    name: '离线同步冲突合并',
    created: '2026-02-18T06:15:00Z',
    modified: '2026-02-18T09:05:00Z',
    messageCount: 22,
    firstMessage: '弱网离线编辑后经常覆盖别人的更新，怎么做冲突合并？',
    lastMessage: '改成字段级 CRDT 合并，冲突工单下降 82%。',
    assistantSummary: '将离线同步从整文档覆盖改为字段级 CRDT。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'simulate_conflict_merge',
    toolArgs: { users: 3, operations: 500 },
    toolOutput: '最后写入覆盖策略在高并发编辑场景冲突损失最高。',
    keywords: ['offline', 'CRDT', 'sync', 'merge'],
    tokenUsage: { input: 18100, output: 8600, cacheRead: 1500, cacheWrite: 520 },
    includeBranchSummary: true,
  },
  {
    id: 'demo-010',
    path: '/demo/infra/session-010.jsonl',
    cwd: '/Users/demo/infra-ops',
    name: '发布流水线并行化',
    created: '2026-02-20T02:05:00Z',
    modified: '2026-02-20T04:40:00Z',
    messageCount: 24,
    firstMessage: 'CI 总时长 42 分钟，想压到 20 分钟以内。',
    lastMessage: '并行矩阵与缓存命中优化后，主分支平均 17.6 分钟。',
    assistantSummary: '拆分串行步骤并提升缓存命中率。',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'profile_ci_jobs',
    toolArgs: { workflow: 'main-ci', lastRuns: 30 },
    toolOutput: 'lint/test/build 串行执行，且依赖缓存 key 波动较大。',
    keywords: ['CI', 'pipeline', 'parallel', 'cache'],
    tokenUsage: { input: 11200, output: 5100, cacheRead: 960, cacheWrite: 240 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-011',
    path: '/demo/ai/session-011.jsonl',
    cwd: '/Users/demo/ai-assistant',
    name: '工具调用失败兜底策略',
    created: '2026-02-23T09:55:00Z',
    modified: '2026-02-23T12:45:00Z',
    messageCount: 26,
    firstMessage: '工具超时后回复很差，想给用户更稳的兜底体验。',
    lastMessage: '新增多级 fallback 后，失败场景满意度提升到 4.6/5。',
    assistantSummary: '引入超时兜底、重试和结果降级模板。',
    model: 'claude-3-haiku',
    provider: 'anthropic',
    toolName: 'call_provider_with_timeout',
    toolArgs: { timeoutMs: 4200, retries: 2 },
    toolOutput: '首轮请求 4.9s 超时，重试成功率 76%，建议启用降级提示。',
    keywords: ['fallback', 'timeout', 'tool call', 'resilience'],
    tokenUsage: { input: 13200, output: 6400, cacheRead: 1010, cacheWrite: 330 },
    includeToolError: true,
    includeBranchSummary: true,
  },
  {
    id: 'demo-012',
    path: '/demo/pi-manager/session-012.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Demo 模式能力补全',
    created: '2026-02-26T07:25:00Z',
    modified: '2026-02-26T13:18:00Z',
    messageCount: 41,
    firstMessage: '希望 demo 可以覆盖标签、收藏、会话详情和全文检索。',
    lastMessage: '已拆分 demo 引擎并接入关键模块，演示路径完整。',
    assistantSummary: '完成 demo data provider 拆分和全链路接入。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'search_context',
    toolArgs: { scope: 'frontend', keywords: ['demo', 'mock', 'search'] },
    toolOutput: '定位到 useSessions/useFavorites/useTags/useSessionViewerData 等入口。',
    keywords: ['demo', 'mock', 'full capability', 'refactor'],
    tokenUsage: { input: 35600, output: 18500, cacheRead: 3300, cacheWrite: 1300 },
    includeCompaction: true,
    includeBranchSummary: true,
    includeCustomMessage: true,
    subagent: {
      runs: 2,
      tokens: 12400,
      cost: 0.28,
      model: 'claude-3-haiku',
      agent: 'ui-reviewer',
    },
  },
  {
    id: 'demo-013',
    path: '/demo/analytics/session-013.jsonl',
    cwd: '/Users/demo/analytics-suite',
    name: '多租户权限泄漏修复',
    created: '2026-02-28T10:12:00Z',
    modified: '2026-02-28T12:00:00Z',
    messageCount: 21,
    firstMessage: '客户反馈看到了其他租户报表，排查权限模型。',
    lastMessage: '增加租户边界断言与集成测试后，泄漏风险归零。',
    assistantSummary: '修复缓存层 tenantId 缺失导致的数据越权。',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'trace_request_chain',
    toolArgs: { requestId: 'req-tenant-leak-2241' },
    toolOutput: 'report cache key 未包含 tenantId，命中跨租户结果。',
    keywords: ['multi-tenant', 'authorization', 'cache key'],
    tokenUsage: { input: 17600, output: 8200, cacheRead: 1400, cacheWrite: 460 },
    includeToolError: true,
  },
  {
    id: 'demo-014',
    path: '/demo/mobile/session-014.jsonl',
    cwd: '/Users/demo/mobile-superapp',
    name: '消息中心红点一致性',
    created: '2026-03-01T05:40:00Z',
    modified: '2026-03-01T08:32:00Z',
    messageCount: 23,
    firstMessage: '多端登录后红点状态不同步，用户投诉很多。',
    lastMessage: '统一状态机 + 事件序列号后，多端一致率提升到 99.7%。',
    assistantSummary: '引入事件序列号并统一读写时序。',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'replay_event_log',
    toolArgs: { stream: 'notification', count: 5000 },
    toolOutput: 'iOS 前台读标记比服务端 ACK 提前提交，导致回滚。',
    keywords: ['notification', 'badge', 'state machine', 'sync'],
    tokenUsage: { input: 12600, output: 5900, cacheRead: 980, cacheWrite: 260 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-015',
    path: '/demo/infra/session-015.jsonl',
    cwd: '/Users/demo/infra-ops',
    name: '日志采样策略调优',
    created: '2026-03-02T01:58:00Z',
    modified: '2026-03-02T04:20:00Z',
    messageCount: 18,
    firstMessage: '日志成本爆了，想在不影响排障的前提下降 30%。',
    lastMessage: '按流量与错误等级分层采样后，成本下降 38%。',
    assistantSummary: '建立分层采样策略兼顾成本与可观测性。',
    model: 'claude-3-haiku',
    provider: 'anthropic',
    toolName: 'estimate_log_cost',
    toolArgs: { services: 42, period: '7d' },
    toolOutput: 'debug 日志占比 63%，高峰期重复字段过多。',
    keywords: ['logging', 'sampling', 'cost', 'observability'],
    tokenUsage: { input: 9100, output: 4300, cacheRead: 720, cacheWrite: 180 },
    includeCompaction: true,
  },
  {
    id: 'demo-016',
    path: '/demo/pi-manager/session-016.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: '命令面板消息检索优化',
    created: '2026-03-03T06:10:00Z',
    modified: '2026-03-03T09:55:00Z',
    messageCount: 28,
    firstMessage: 'command palette 的消息检索结果质量不稳定。',
    lastMessage: '增加片段抽取和排序策略后，Top3 命中率提升到 92%。',
    assistantSummary: '优化全文检索片段与结果排序。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'full_text_search',
    toolArgs: { roleFilter: 'all', pageSize: 40 },
    toolOutput: '现有排序过度依赖分数，缺少时间和上下文相关性。',
    keywords: ['command palette', 'full text search', 'ranking'],
    tokenUsage: { input: 22300, output: 10100, cacheRead: 1700, cacheWrite: 580 },
    includeBranchSummary: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-017',
    path: '/demo/pi-manager/session-017.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Bash 构建失败诊断',
    created: '2026-03-03T10:05:00Z',
    modified: '2026-03-03T11:28:00Z',
    messageCount: 16,
    firstMessage: 'CI 在 lint 前就失败了，帮我快速定位 bash 执行链路问题。',
    lastMessage: '补齐环境变量和依赖缓存后，构建恢复稳定。',
    assistantSummary: '定位到 shell 环境差异导致的命令失败并给出修复步骤。',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'bash',
    toolArgs: { command: 'pnpm build --mode production && pnpm run lint' },
    toolOutput: ' ELIFECYCLE  Command failed with exit code 1.\nError: Cannot find module @types/node\nHint: run `pnpm install --frozen-lockfile` before build.',
    keywords: ['bash', 'build', 'CI', 'lint'],
    tokenUsage: { input: 7800, output: 3600, cacheRead: 620, cacheWrite: 150 },
    includeToolError: true,
  },
  {
    id: 'demo-018',
    path: '/demo/pi-manager/session-018.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Read 文件片段校验',
    created: '2026-03-03T11:40:00Z',
    modified: '2026-03-03T12:26:00Z',
    messageCount: 14,
    firstMessage: '我想确认 ToolCallList 的分支逻辑，帮我读一下关键代码。',
    lastMessage: '已确认 read/write/edit/subagent 分支和字段映射一致。',
    assistantSummary: '通过 read 工具读取代码片段并核对渲染入口。',
    model: 'claude-3-haiku',
    provider: 'anthropic',
    toolName: 'read',
    toolArgs: { file_path: 'src/components/ToolCallList.tsx', offset: 48, limit: 78 },
    toolOutput: 'switch(name) 分支命中 bash/read/write/edit/subagent，默认走 GenericToolCall。',
    keywords: ['read', 'tool', 'render', 'toolcalllist'],
    tokenUsage: { input: 6400, output: 2900, cacheRead: 480, cacheWrite: 130 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-019',
    path: '/demo/pi-manager/session-019.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Write JSONL Mock 模板',
    created: '2026-03-03T12:38:00Z',
    modified: '2026-03-03T13:12:00Z',
    messageCount: 12,
    firstMessage: '给我写一个可直接渲染的 JSONL mock，会话要包含 tool 调用。',
    lastMessage: '已输出可渲染模板，导入后可直接回放完整会话。',
    assistantSummary: '通过 write 工具写入 JSONL 模板并说明字段约束。',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'write',
    toolArgs: {
      file_path: 'src/demo/mock/full-session-tooling.jsonl',
      content: '{"type":"session","id":"mock-session"}\n{"type":"message","id":"mock-user","message":{"role":"user","content":[{"type":"text","text":"请演示 tool 渲染"}]}}\n{"type":"message","id":"mock-assistant","message":{"role":"assistant","content":[{"type":"toolCall","id":"tc-1","name":"bash","arguments":{"command":"echo hi"}}]}}',
    },
    toolOutput: 'Wrote 3 lines to src/demo/mock/full-session-tooling.jsonl',
    keywords: ['write', 'jsonl', 'mock', 'session'],
    tokenUsage: { input: 5900, output: 2700, cacheRead: 420, cacheWrite: 120 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-020',
    path: '/demo/pi-manager/session-020.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Edit Diff 渲染回归',
    created: '2026-03-03T13:26:00Z',
    modified: '2026-03-03T14:10:00Z',
    messageCount: 15,
    firstMessage: '编辑工具卡片没显示差异，帮我构造一份可回归 diff 数据。',
    lastMessage: '差异视图与回退说明都正常渲染，回归通过。',
    assistantSummary: '提供可解析 diff，验证 EditExecution 组件渲染链路。',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'edit',
    toolArgs: { file_path: 'src/components/ToolCallList.tsx' },
    toolOutput: 'Applied patch to src/components/ToolCallList.tsx with 3 additions and 1 removal.',
    keywords: ['edit', 'diff', 'render', 'regression'],
    tokenUsage: { input: 7200, output: 3400, cacheRead: 560, cacheWrite: 140 },
    includeBranchSummary: true,
  },
]

export const DEMO_TAGS: Tag[] = [
  {
    id: 'tag-frontend',
    name: 'Frontend',
    color: '#4f46e5',
    icon: 'Layout',
    sortOrder: 0,
    isBuiltin: false,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'tag-backend',
    name: 'Backend',
    color: '#0ea5e9',
    icon: 'Server',
    sortOrder: 1,
    isBuiltin: false,
    createdAt: '2026-01-20T10:01:00Z',
  },
  {
    id: 'tag-devops',
    name: 'DevOps',
    color: '#f59e0b',
    icon: 'Cloud',
    sortOrder: 2,
    isBuiltin: false,
    createdAt: '2026-01-20T10:02:00Z',
  },
  {
    id: 'tag-ai',
    name: 'AI',
    color: '#22c55e',
    icon: 'Bot',
    sortOrder: 3,
    isBuiltin: false,
    createdAt: '2026-01-20T10:03:00Z',
  },
  {
    id: 'tag-performance',
    name: 'Performance',
    color: '#ef4444',
    icon: 'Gauge',
    sortOrder: 4,
    isBuiltin: false,
    createdAt: '2026-01-20T10:04:00Z',
    parentId: 'tag-backend',
    autoRules: 'slow\nlatency\nperformance\n优化',
  },
  {
    id: 'tag-reliability',
    name: 'Reliability',
    color: '#14b8a6',
    icon: 'Shield',
    sortOrder: 5,
    isBuiltin: false,
    createdAt: '2026-01-20T10:05:00Z',
    parentId: 'tag-devops',
    autoRules: 'incident\ntimeout\nreconnect\n回滚',
  },
  {
    id: 'tag-search',
    name: 'Search',
    color: '#a855f7',
    icon: 'Search',
    sortOrder: 6,
    isBuiltin: false,
    createdAt: '2026-01-20T10:06:00Z',
    parentId: 'tag-ai',
    autoRules: 'search\nretrieval\nRAG\n检索',
  },
  {
    id: 'tag-release',
    name: 'Release',
    color: '#10b981',
    icon: 'Rocket',
    sortOrder: 7,
    isBuiltin: false,
    createdAt: '2026-01-20T10:07:00Z',
    autoRules: 'release\n发布\npipeline',
  },
]

export const DEMO_SESSION_TAGS: SessionTag[] = [
  { sessionId: 'demo-001', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-03T11:43:00Z' },
  { sessionId: 'demo-001', tagId: 'tag-performance', position: 1, assignedAt: '2026-02-03T11:44:00Z' },
  { sessionId: 'demo-002', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-04T10:21:00Z' },
  { sessionId: 'demo-002', tagId: 'tag-performance', position: 1, assignedAt: '2026-02-04T10:22:00Z' },
  { sessionId: 'demo-003', tagId: 'tag-performance', position: 0, assignedAt: '2026-02-06T09:13:00Z' },
  { sessionId: 'demo-003', tagId: 'tag-backend', position: 1, assignedAt: '2026-02-06T09:14:00Z' },
  { sessionId: 'demo-004', tagId: 'tag-frontend', position: 0, assignedAt: '2026-02-08T06:49:00Z' },
  { sessionId: 'demo-005', tagId: 'tag-devops', position: 0, assignedAt: '2026-02-10T05:31:00Z' },
  { sessionId: 'demo-005', tagId: 'tag-reliability', position: 1, assignedAt: '2026-02-10T05:32:00Z' },
  { sessionId: 'demo-006', tagId: 'tag-ai', position: 0, assignedAt: '2026-02-12T12:06:00Z' },
  { sessionId: 'demo-006', tagId: 'tag-search', position: 1, assignedAt: '2026-02-12T12:07:00Z' },
  { sessionId: 'demo-007', tagId: 'tag-reliability', position: 0, assignedAt: '2026-02-14T12:56:00Z' },
  { sessionId: 'demo-008', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-16T08:16:00Z' },
  { sessionId: 'demo-009', tagId: 'tag-frontend', position: 0, assignedAt: '2026-02-18T09:06:00Z' },
  { sessionId: 'demo-010', tagId: 'tag-devops', position: 0, assignedAt: '2026-02-20T04:41:00Z' },
  { sessionId: 'demo-010', tagId: 'tag-release', position: 1, assignedAt: '2026-02-20T04:42:00Z' },
  { sessionId: 'demo-011', tagId: 'tag-ai', position: 0, assignedAt: '2026-02-23T12:46:00Z' },
  { sessionId: 'demo-011', tagId: 'tag-reliability', position: 1, assignedAt: '2026-02-23T12:47:00Z' },
  { sessionId: 'demo-012', tagId: 'tag-release', position: 0, assignedAt: '2026-02-26T13:19:00Z' },
  { sessionId: 'demo-012', tagId: 'tag-search', position: 1, assignedAt: '2026-02-26T13:20:00Z' },
  { sessionId: 'demo-013', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-28T12:01:00Z' },
  { sessionId: 'demo-014', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-01T08:33:00Z' },
  { sessionId: 'demo-015', tagId: 'tag-devops', position: 0, assignedAt: '2026-03-02T04:21:00Z' },
  { sessionId: 'demo-016', tagId: 'tag-search', position: 0, assignedAt: '2026-03-03T09:56:00Z' },
  { sessionId: 'demo-017', tagId: 'tag-devops', position: 0, assignedAt: '2026-03-03T11:29:00Z' },
  { sessionId: 'demo-017', tagId: 'tag-release', position: 1, assignedAt: '2026-03-03T11:30:00Z' },
  { sessionId: 'demo-018', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-03T12:27:00Z' },
  { sessionId: 'demo-018', tagId: 'tag-search', position: 1, assignedAt: '2026-03-03T12:28:00Z' },
  { sessionId: 'demo-019', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-03T13:13:00Z' },
  { sessionId: 'demo-019', tagId: 'tag-release', position: 1, assignedAt: '2026-03-03T13:14:00Z' },
  { sessionId: 'demo-020', tagId: 'tag-backend', position: 0, assignedAt: '2026-03-03T14:11:00Z' },
  { sessionId: 'demo-020', tagId: 'tag-frontend', position: 1, assignedAt: '2026-03-03T14:12:00Z' },
]

export const DEMO_FAVORITES: FavoriteItem[] = [
  {
    id: 'demo-001',
    type: 'session',
    name: 'Checkout 风险规则联调',
    path: '/demo/commerce/session-001.jsonl',
    addedAt: '2026-02-03T11:45:00Z',
  },
  {
    id: 'demo-006',
    type: 'session',
    name: 'RAG 召回质量回归',
    path: '/demo/ai/session-006.jsonl',
    addedAt: '2026-02-12T12:08:00Z',
  },
  {
    id: 'demo-012',
    type: 'session',
    name: 'Demo 模式能力补全',
    path: '/demo/pi-manager/session-012.jsonl',
    addedAt: '2026-02-26T13:21:00Z',
  },
  {
    id: 'fav-project-commerce',
    type: 'project',
    name: 'commerce-platform',
    path: '/Users/demo/commerce-platform',
    addedAt: '2026-02-18T09:10:00Z',
  },
]
