import type { FavoriteItem, SessionTag, Tag } from '@/types'

export interface DemoTokenUsageSeed {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

export interface DemoSubagentSeed {
  runs: number
  tokens: number
  cost: number
  model: string
  agent: string
}

export interface DemoSessionSeed {
  id: string
  path: string
  cwd: string
  name: string
  created: string
  modified: string
  messageCount: number
  firstMessage: string
  lastMessage: string
  assistantSummary: string
  model: string
  provider: string
  toolName: string
  toolArgs: Record<string, unknown>
  toolOutput: string
  keywords: string[]
  tokenUsage: DemoTokenUsageSeed
  includeCompaction?: boolean
  includeBranchSummary?: boolean
  includeCustomMessage?: boolean
  includeToolError?: boolean
  subagent?: DemoSubagentSeed
}

export const TOKEN_RATES: Record<string, { input: number; output: number }> = {
  'gpt-4o': { input: 5, output: 15 },
  'gpt-4o-mini': { input: 0.15, output: 0.6 },
  'claude-3-5-sonnet': { input: 3, output: 15 },
  'claude-3-haiku': { input: 0.25, output: 1.25 },
  default: { input: 1, output: 2 },
}

export const DEMO_SESSION_SEEDS: DemoSessionSeed[] = [
  {
    id: 'demo-001',
    path: '/demo/commerce/session-001.jsonl',
    cwd: '/Users/demo/commerce-platform',
    name: 'Checkout Risk Rule Alignment',
    created: '2026-02-03T09:10:00Z',
    modified: '2026-02-03T11:42:00Z',
    messageCount: 34,
    firstMessage: 'Payment success dropped to 91%. Help me locate false positives in checkout risk rules.',
    lastMessage: 'Rolled out a canary strategy and false positives dropped from 8.7% to 1.4%.',
    assistantSummary: 'Found rule-order conflicts and proposed a safe canary rollback plan.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'query_metrics',
    toolArgs: { dashboard: 'checkout', window: '24h' },
    toolOutput: 'High-risk rule v3 spiked on iOS traffic with a 31.2% peak trigger rate.',
    keywords: ['checkout', 'risk', 'canary', 'payment', 'false-positive'],
    tokenUsage: { input: 28500, output: 11200, cacheRead: 2400, cacheWrite: 800 },
    includeBranchSummary: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-002',
    path: '/demo/commerce/session-002.jsonl',
    cwd: '/Users/demo/commerce-platform',
    name: 'Inventory Deduction Concurrency Fix',
    created: '2026-02-04T07:45:00Z',
    modified: '2026-02-04T10:20:00Z',
    messageCount: 27,
    firstMessage: 'Flash-sale inventory went negative. Need a low-risk fix.',
    lastMessage: 'After optimistic locking + retries, stock consistency recovered and p95 latency only rose by 4ms.',
    assistantSummary: 'Fixed overselling with row versioning and retry-on-conflict.',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'explain_sql_plan',
    toolArgs: { table: 'inventory', statement: 'update ... where version = ?' },
    toolOutput: 'Query plan shows PK hit; conflicts mostly come from hot-SKU row locks.',
    keywords: ['inventory', 'concurrency', 'flash-sale', 'optimistic-lock', 'retry'],
    tokenUsage: { input: 21400, output: 9800, cacheRead: 1800, cacheWrite: 620 },
    includeCompaction: true,
  },
  {
    id: 'demo-003',
    path: '/demo/analytics/session-003.jsonl',
    cwd: '/Users/demo/analytics-suite',
    name: 'Analytics Dashboard Slow Query Tuning',
    created: '2026-02-06T05:20:00Z',
    modified: '2026-02-06T09:12:00Z',
    messageCount: 31,
    firstMessage: 'BI home dashboard takes 18s to load. Help me redesign query layers.',
    lastMessage: 'Hot/cold tiering cut first paint to 2.8s and CPU peak by 37%.',
    assistantSummary: 'Used pre-aggregation and data tiering to reduce response time.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'profile_query',
    toolArgs: { queryId: 'bi_home_top_cards' },
    toolOutput: 'Most cost comes from cross-month aggregation and JSON field functions.',
    keywords: ['dashboard', 'slow query', 'pre-aggregation', 'BI'],
    tokenUsage: { input: 30100, output: 14500, cacheRead: 2600, cacheWrite: 950 },
    includeBranchSummary: true,
  },
  {
    id: 'demo-004',
    path: '/demo/mobile/session-004.jsonl',
    cwd: '/Users/demo/mobile-superapp',
    name: 'React Native Bundle Size Reduction',
    created: '2026-02-08T03:35:00Z',
    modified: '2026-02-08T06:48:00Z',
    messageCount: 19,
    firstMessage: 'Android bundle grew from 64MB to 96MB. Need it back under 70MB within a week.',
    lastMessage: 'Removed redundant dependencies and split assets; release bundle is now 68MB.',
    assistantSummary: 'Reduced package size via dependency pruning and asset splitting.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'analyze_bundle',
    toolArgs: { platform: 'android', variant: 'release' },
    toolOutput: 'Duplicate image libraries plus locale assets were bundled without language splitting.',
    keywords: ['React Native', 'bundle', 'Android', 'size'],
    tokenUsage: { input: 9800, output: 4200, cacheRead: 900, cacheWrite: 210 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-005',
    path: '/demo/infra/session-005.jsonl',
    cwd: '/Users/demo/infra-ops',
    name: 'K8s Node Flapping Incident',
    created: '2026-02-10T01:10:00Z',
    modified: '2026-02-10T05:30:00Z',
    messageCount: 36,
    firstMessage: 'Nodes went NotReady repeatedly overnight, impacting 3 critical services.',
    lastMessage: 'Root cause was a race in CNI upgrade scripts; locking and rollback were added.',
    assistantSummary: 'Completed incident review and hardened release pipeline guards.',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'kubectl_events',
    toolArgs: { namespace: 'core', since: '6h' },
    toolOutput: 'Network plugin restarts overlapped with rolling deploy windows, causing probe storms.',
    keywords: ['k8s', 'node', 'NotReady', 'CNI', 'incident'],
    tokenUsage: { input: 32400, output: 16900, cacheRead: 3000, cacheWrite: 1100 },
    includeCompaction: true,
    includeBranchSummary: true,
  },
  {
    id: 'demo-006',
    path: '/demo/ai/session-006.jsonl',
    cwd: '/Users/demo/ai-assistant',
    name: 'RAG Recall Quality Regression',
    created: '2026-02-12T08:30:00Z',
    modified: '2026-02-12T12:05:00Z',
    messageCount: 29,
    firstMessage: 'After shipping a new embedding model, FAQ hit rate fell from 86% to 63%.',
    lastMessage: 'After chunking and rerank tuning, hit rate recovered to 88.5%.',
    assistantSummary: 'Recovered recall quality by adjusting chunk strategy and rerank parameters.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'compare_retrieval_runs',
    toolArgs: { baseline: 'embed-v2', candidate: 'embed-v3' },
    toolOutput: 'v3 over-relies on semantic proximity for short queries and loses long-document recall.',
    keywords: ['RAG', 'embedding', 'rerank', 'recall'],
    tokenUsage: { input: 26700, output: 12800, cacheRead: 2200, cacheWrite: 760 },
    includeBranchSummary: true,
    subagent: {
      runs: 3,
      tokens: 18600,
      cost: 0.42,
      model: 'gpt-4o-mini',
      agent: 'retrieval-auditor',
    },
  },
  {
    id: 'demo-007',
    path: '/demo/analytics/session-007.jsonl',
    cwd: '/Users/demo/analytics-suite',
    name: 'SSE Message Loss Recovery',
    created: '2026-02-14T11:00:00Z',
    modified: '2026-02-14T12:55:00Z',
    messageCount: 17,
    firstMessage: 'Realtime alert dashboard has random gaps; suspect SSE reconnect misses deltas.',
    lastMessage: 'Reconnect compensation now uses Last-Event-ID + replay, and gaps are gone.',
    assistantSummary: 'Added incremental replay during reconnect windows.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'inspect_event_stream',
    toolArgs: { stream: 'alerts', sampleSeconds: 120 },
    toolOutput: 'Events were written during 2-4s disconnect windows but the client had no backfill logic.',
    keywords: ['SSE', 'reconnect', 'alerts', 'replay'],
    tokenUsage: { input: 8600, output: 3900, cacheRead: 780, cacheWrite: 190 },
    includeToolError: true,
  },
  {
    id: 'demo-008',
    path: '/demo/commerce/session-008.jsonl',
    cwd: '/Users/demo/commerce-platform',
    name: 'Coupon Rule Engine Refactor',
    created: '2026-02-16T04:20:00Z',
    modified: '2026-02-16T08:15:00Z',
    messageCount: 33,
    firstMessage: 'Coupon stacking logic is too chaotic and keeps applying wrong discounts during campaigns.',
    lastMessage: 'After shipping the new rule DSL, regression pass rate improved from 71% to 99%.',
    assistantSummary: 'Abstracted condition trees into a DSL and added a full rule matrix.',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'generate_rule_matrix',
    toolArgs: { scenarios: 120, channels: ['app', 'h5', 'mini'] },
    toolOutput: 'Detected 23 rule conflicts, mainly around threshold discounts and coupon-pack priority.',
    keywords: ['coupon', 'DSL', 'rules engine', 'discount'],
    tokenUsage: { input: 29600, output: 14200, cacheRead: 2500, cacheWrite: 870 },
    includeCompaction: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-009',
    path: '/demo/mobile/session-009.jsonl',
    cwd: '/Users/demo/mobile-superapp',
    name: 'Offline Sync Conflict Merge',
    created: '2026-02-18T06:15:00Z',
    modified: '2026-02-18T09:05:00Z',
    messageCount: 22,
    firstMessage: 'Offline edits on weak networks keep overwriting other users. How should conflicts be merged?',
    lastMessage: 'Switched to field-level CRDT merge and conflict tickets dropped by 82%.',
    assistantSummary: 'Moved offline sync from whole-document overwrite to field-level CRDT.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'simulate_conflict_merge',
    toolArgs: { users: 3, operations: 500 },
    toolOutput: 'Last-write-wins causes the highest data loss under concurrent editing.',
    keywords: ['offline', 'CRDT', 'sync', 'merge'],
    tokenUsage: { input: 18100, output: 8600, cacheRead: 1500, cacheWrite: 520 },
    includeBranchSummary: true,
  },
  {
    id: 'demo-010',
    path: '/demo/infra/session-010.jsonl',
    cwd: '/Users/demo/infra-ops',
    name: 'Release Pipeline Parallelization',
    created: '2026-02-20T02:05:00Z',
    modified: '2026-02-20T04:40:00Z',
    messageCount: 24,
    firstMessage: 'CI takes 42 minutes end-to-end; the target is under 20.',
    lastMessage: 'Parallel matrix jobs plus cache tuning brought main-branch average down to 17.6 minutes.',
    assistantSummary: 'Split serial stages and improved dependency cache hit rates.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'profile_ci_jobs',
    toolArgs: { workflow: 'main-ci', lastRuns: 30 },
    toolOutput: 'lint/test/build were serialized, and dependency cache keys changed too often.',
    keywords: ['CI', 'pipeline', 'parallel', 'cache'],
    tokenUsage: { input: 11200, output: 5100, cacheRead: 960, cacheWrite: 240 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-011',
    path: '/demo/ai/session-011.jsonl',
    cwd: '/Users/demo/ai-assistant',
    name: 'Tool Failure Fallback Strategy',
    created: '2026-02-23T09:55:00Z',
    modified: '2026-02-23T12:45:00Z',
    messageCount: 26,
    firstMessage: 'Replies degrade badly after tool timeouts; need a more reliable fallback UX.',
    lastMessage: 'After adding multi-level fallbacks, failure-case satisfaction reached 4.6/5.',
    assistantSummary: 'Introduced timeout fallback, retries, and degraded response templates.',
    model: 'claude-3-haiku',
    provider: 'anthropic',
    toolName: 'call_provider_with_timeout',
    toolArgs: { timeoutMs: 4200, retries: 2 },
    toolOutput: 'First request timed out at 4.9s; retry success is 76%; recommend graceful degradation messaging.',
    keywords: ['fallback', 'timeout', 'tool call', 'resilience'],
    tokenUsage: { input: 13200, output: 6400, cacheRead: 1010, cacheWrite: 330 },
    includeToolError: true,
    includeBranchSummary: true,
  },
  {
    id: 'demo-012',
    path: '/demo/pi-manager/session-012.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Demo Mode Coverage Expansion',
    created: '2026-02-26T07:25:00Z',
    modified: '2026-02-26T13:18:00Z',
    messageCount: 41,
    firstMessage: 'I want demo mode to cover tags, favorites, session details, and full-text search.',
    lastMessage: 'The demo engine is now modularized and wired into key modules end-to-end.',
    assistantSummary: 'Completed modular demo providers and end-to-end integration.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'search_context',
    toolArgs: { scope: 'frontend', keywords: ['demo', 'mock', 'search'] },
    toolOutput: 'Located integration points in useSessions/useFavorites/useTags/useSessionViewerData.',
    keywords: ['demo', 'mock', 'full capability', 'refactor'],
    tokenUsage: { input: 35600, output: 18500, cacheRead: 3300, cacheWrite: 1300 },
    includeCompaction: true,
    includeBranchSummary: true,
    includeCustomMessage: true,
    subagent: {
      runs: 2,
      tokens: 12400,
      cost: 0.28,
      model: 'claude-3-haiku',
      agent: 'ui-reviewer',
    },
  },
  {
    id: 'demo-013',
    path: '/demo/analytics/session-013.jsonl',
    cwd: '/Users/demo/analytics-suite',
    name: 'Multi-Tenant Data Leak Fix',
    created: '2026-02-28T10:12:00Z',
    modified: '2026-02-28T12:00:00Z',
    messageCount: 21,
    firstMessage: 'A customer can see another tenant\'s reports. Audit the authorization model.',
    lastMessage: 'Added tenant-boundary assertions and integration tests; leak risk is now zero.',
    assistantSummary: 'Fixed missing tenantId in the cache layer that caused cross-tenant data access.',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'trace_request_chain',
    toolArgs: { requestId: 'req-tenant-leak-2241' },
    toolOutput: 'Report cache key missed tenantId and returned cross-tenant hits.',
    keywords: ['multi-tenant', 'authorization', 'cache key'],
    tokenUsage: { input: 17600, output: 8200, cacheRead: 1400, cacheWrite: 460 },
    includeToolError: true,
  },
  {
    id: 'demo-014',
    path: '/demo/mobile/session-014.jsonl',
    cwd: '/Users/demo/mobile-superapp',
    name: 'Notification Badge Consistency',
    created: '2026-03-01T05:40:00Z',
    modified: '2026-03-01T08:32:00Z',
    messageCount: 23,
    firstMessage: 'Badge state is inconsistent across devices after multi-login, and users complain frequently.',
    lastMessage: 'Unified state machine + event sequence numbers raised cross-device consistency to 99.7%.',
    assistantSummary: 'Introduced event sequence IDs and unified read/write ordering.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'replay_event_log',
    toolArgs: { stream: 'notification', count: 5000 },
    toolOutput: 'iOS foreground read-mark was committed before server ACK and then rolled back.',
    keywords: ['notification', 'badge', 'state machine', 'sync'],
    tokenUsage: { input: 12600, output: 5900, cacheRead: 980, cacheWrite: 260 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-015',
    path: '/demo/infra/session-015.jsonl',
    cwd: '/Users/demo/infra-ops',
    name: 'Log Sampling Strategy Tuning',
    created: '2026-03-02T01:58:00Z',
    modified: '2026-03-02T04:20:00Z',
    messageCount: 18,
    firstMessage: 'Logging cost exploded; need a 30% reduction without hurting troubleshooting.',
    lastMessage: 'Layered sampling by traffic and error severity reduced cost by 38%.',
    assistantSummary: 'Built a tiered sampling strategy to balance cost and observability.',
    model: 'claude-3-haiku',
    provider: 'anthropic',
    toolName: 'estimate_log_cost',
    toolArgs: { services: 42, period: '7d' },
    toolOutput: 'Debug logs account for 63% of volume, with too many repeated fields at peak.',
    keywords: ['logging', 'sampling', 'cost', 'observability'],
    tokenUsage: { input: 9100, output: 4300, cacheRead: 720, cacheWrite: 180 },
    includeCompaction: true,
  },
  {
    id: 'demo-016',
    path: '/demo/pi-manager/session-016.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Command Palette Search Quality',
    created: '2026-03-03T06:10:00Z',
    modified: '2026-03-03T09:55:00Z',
    messageCount: 28,
    firstMessage: 'Message search quality in the command palette is unstable.',
    lastMessage: 'After snippet extraction and ranking updates, Top-3 hit rate improved to 92%.',
    assistantSummary: 'Optimized full-text snippets and result ranking.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'full_text_search',
    toolArgs: { roleFilter: 'all', pageSize: 40 },
    toolOutput: 'Current ranking overweights score and lacks recency/context relevance.',
    keywords: ['command palette', 'full text search', 'ranking'],
    tokenUsage: { input: 22300, output: 10100, cacheRead: 1700, cacheWrite: 580 },
    includeBranchSummary: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-017',
    path: '/demo/pi-manager/session-017.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Bash Build Failure Triage',
    created: '2026-03-03T10:05:00Z',
    modified: '2026-03-03T11:28:00Z',
    messageCount: 16,
    firstMessage: 'CI fails before lint. Help me quickly trace the bash execution chain.',
    lastMessage: 'Added environment variables and dependency cache setup; builds are stable again.',
    assistantSummary: 'Traced shell environment differences causing command failures and proposed fix steps.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'bash',
    toolArgs: { command: 'pnpm build --mode production && pnpm run lint' },
    toolOutput: ' ELIFECYCLE  Command failed with exit code 1.\nError: Cannot find module @types/node\nHint: run `pnpm install --frozen-lockfile` before build.',
    keywords: ['bash', 'build', 'CI', 'lint'],
    tokenUsage: { input: 7800, output: 3600, cacheRead: 620, cacheWrite: 150 },
    includeToolError: true,
  },
  {
    id: 'demo-018',
    path: '/demo/pi-manager/session-018.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Read Snippet Verification',
    created: '2026-03-03T11:40:00Z',
    modified: '2026-03-03T12:26:00Z',
    messageCount: 14,
    firstMessage: 'I want to verify ToolCallList branching. Please read the key code path.',
    lastMessage: 'Confirmed read/write/edit/subagent branches and field mapping are consistent.',
    assistantSummary: 'Used the read tool output to validate rendering entry points.',
    model: 'claude-3-haiku',
    provider: 'anthropic',
    toolName: 'read',
    toolArgs: { file_path: 'src/components/ToolCallList.tsx', offset: 48, limit: 78 },
    toolOutput: 'switch(name) matches bash/read/write/edit/subagent; default falls back to GenericToolCall.',
    keywords: ['read', 'tool', 'render', 'toolcalllist'],
    tokenUsage: { input: 6400, output: 2900, cacheRead: 480, cacheWrite: 130 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-019',
    path: '/demo/pi-manager/session-019.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Write JSONL Mock Template',
    created: '2026-03-03T12:38:00Z',
    modified: '2026-03-03T13:12:00Z',
    messageCount: 12,
    firstMessage: 'Write a directly renderable JSONL mock session that includes tool calls.',
    lastMessage: 'Generated a render-ready template that replays a full session after import.',
    assistantSummary: 'Generated a JSONL template via write tool and documented required fields.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'write',
    toolArgs: {
      file_path: 'src/demo/mock/full-session-tooling.jsonl',
      content: '{"type":"session","id":"mock-session"}\n{"type":"message","id":"mock-user","message":{"role":"user","content":[{"type":"text","text":"Please demonstrate tool rendering"}]}}\n{"type":"message","id":"mock-assistant","message":{"role":"assistant","content":[{"type":"toolCall","id":"tc-1","name":"bash","arguments":{"command":"echo hi"}}]}}',
    },
    toolOutput: 'Wrote 3 lines to src/demo/mock/full-session-tooling.jsonl',
    keywords: ['write', 'jsonl', 'mock', 'session'],
    tokenUsage: { input: 5900, output: 2700, cacheRead: 420, cacheWrite: 120 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-020',
    path: '/demo/pi-manager/session-020.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Edit Diff Rendering Regression',
    created: '2026-03-03T13:26:00Z',
    modified: '2026-03-03T14:10:00Z',
    messageCount: 15,
    firstMessage: 'The edit tool card does not show diffs. Build a regression-ready diff sample.',
    lastMessage: 'Diff view and rollback notes now render correctly; regression passed.',
    assistantSummary: 'Provided parseable diff data to validate the EditExecution rendering path.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'edit',
    toolArgs: { file_path: 'src/components/ToolCallList.tsx' },
    toolOutput: 'Applied patch to src/components/ToolCallList.tsx with 3 additions and 1 removal.',
    keywords: ['edit', 'diff', 'render', 'regression'],
    tokenUsage: { input: 7200, output: 3400, cacheRead: 560, cacheWrite: 140 },
    includeBranchSummary: true,
  },
  {
    id: 'demo-021',
    path: '/demo/security/session-021.jsonl',
    cwd: '/Users/demo/security-gateway',
    name: 'API Abuse Detection Tuning',
    created: '2026-03-04T02:15:00Z',
    modified: '2026-03-04T05:04:00Z',
    messageCount: 32,
    firstMessage: 'Credential-stuffing traffic bypassed our edge filters overnight. Need a fast mitigation plan.',
    lastMessage: 'Adaptive rate limits + risk scoring blocked 93% of attack traffic with no checkout regression.',
    assistantSummary: 'Combined bot fingerprinting with adaptive limits and a staged rollout.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'analyze_edge_logs',
    toolArgs: { service: 'api-gateway', window: '8h' },
    toolOutput: 'Attackers rotated IPs every 90 seconds and reused a narrow set of device fingerprints.',
    keywords: ['security', 'rate limit', 'abuse detection', 'edge', 'bot'],
    tokenUsage: { input: 24800, output: 12100, cacheRead: 2100, cacheWrite: 700 },
    includeCompaction: true,
    includeBranchSummary: true,
  },
  {
    id: 'demo-022',
    path: '/demo/data/session-022.jsonl',
    cwd: '/Users/demo/data-platform',
    name: 'Warehouse Schema Drift Recovery',
    created: '2026-03-04T06:30:00Z',
    modified: '2026-03-04T09:18:00Z',
    messageCount: 25,
    firstMessage: 'Nightly ETL broke after upstream schema drift. Need a backward-compatible recovery.',
    lastMessage: 'Added contract checks and nullable defaults; pipeline recovered and SLA breach was avoided.',
    assistantSummary: 'Introduced schema contracts and staged migrations to prevent downstream breakage.',
    model: 'claude-3-5-sonnet',
    provider: 'anthropic',
    toolName: 'diff_table_schema',
    toolArgs: { source: 'orders_v2', target: 'warehouse.orders' },
    toolOutput: 'Upstream added 3 columns and changed currency_code from TEXT to ENUM.',
    keywords: ['data warehouse', 'schema drift', 'etl', 'migration'],
    tokenUsage: { input: 16900, output: 7900, cacheRead: 1320, cacheWrite: 420 },
    includeCustomMessage: true,
  },
  {
    id: 'demo-023',
    path: '/demo/frontend/session-023.jsonl',
    cwd: '/Users/demo/design-system',
    name: 'Accessibility Regression Sweep',
    created: '2026-03-04T10:05:00Z',
    modified: '2026-03-04T12:52:00Z',
    messageCount: 30,
    firstMessage: 'A11y audit shows multiple WCAG 2.2 failures after the UI refresh. Need a prioritized fix list.',
    lastMessage: 'Fixed keyboard traps and contrast issues; audit score improved from 71 to 96.',
    assistantSummary: 'Prioritized accessibility fixes by user impact and rollout risk.',
    model: 'gpt-4o-mini',
    provider: 'openai',
    toolName: 'run_a11y_audit',
    toolArgs: { pages: ['dashboard', 'session-viewer', 'settings'], standard: 'WCAG2.2AA' },
    toolOutput: 'Critical findings: missing focus styles, low-contrast badges, and unlabeled icon buttons.',
    keywords: ['frontend', 'a11y', 'wcag', 'design system', 'audit'],
    tokenUsage: { input: 15400, output: 7100, cacheRead: 1180, cacheWrite: 320 },
    includeBranchSummary: true,
    includeCustomMessage: true,
  },
  {
    id: 'demo-024',
    path: '/demo/pi-manager/session-024.jsonl',
    cwd: '/Users/demo/pi-session-manager',
    name: 'Offline Demo Bundle Packaging',
    created: '2026-03-05T01:20:00Z',
    modified: '2026-03-05T04:46:00Z',
    messageCount: 37,
    firstMessage: 'We need a standalone demo page that always boots with rich mock data and zero backend dependency.',
    lastMessage: 'Built a static demo bundle with forced demo mode and documented build + preview commands.',
    assistantSummary: 'Delivered a dedicated demo build mode and validated static deployment behavior.',
    model: 'gpt-4o',
    provider: 'openai',
    toolName: 'vite_build',
    toolArgs: { mode: 'demo', outDir: 'dist-demo' },
    toolOutput: 'Build succeeded: dist-demo/index.html now boots with demo settings and English sample data.',
    keywords: ['demo', 'static html', 'vite', 'build mode', 'mock data'],
    tokenUsage: { input: 28900, output: 14300, cacheRead: 2400, cacheWrite: 860 },
    includeCompaction: true,
    includeBranchSummary: true,
    includeCustomMessage: true,
    subagent: {
      runs: 2,
      tokens: 9400,
      cost: 0.21,
      model: 'gpt-4o-mini',
      agent: 'release-checker',
    },
  },
]

export const DEMO_TAGS: Tag[] = [
  {
    id: 'tag-frontend',
    name: 'Frontend',
    color: '#4f46e5',
    icon: 'Layout',
    sortOrder: 0,
    isBuiltin: false,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'tag-backend',
    name: 'Backend',
    color: '#0ea5e9',
    icon: 'Server',
    sortOrder: 1,
    isBuiltin: false,
    createdAt: '2026-01-20T10:01:00Z',
  },
  {
    id: 'tag-devops',
    name: 'DevOps',
    color: '#f59e0b',
    icon: 'Cloud',
    sortOrder: 2,
    isBuiltin: false,
    createdAt: '2026-01-20T10:02:00Z',
  },
  {
    id: 'tag-ai',
    name: 'AI',
    color: '#22c55e',
    icon: 'Bot',
    sortOrder: 3,
    isBuiltin: false,
    createdAt: '2026-01-20T10:03:00Z',
  },
  {
    id: 'tag-performance',
    name: 'Performance',
    color: '#ef4444',
    icon: 'Gauge',
    sortOrder: 4,
    isBuiltin: false,
    createdAt: '2026-01-20T10:04:00Z',
    parentId: 'tag-backend',
    autoRules: 'slow\nlatency\nperformance\noptimize',
  },
  {
    id: 'tag-reliability',
    name: 'Reliability',
    color: '#14b8a6',
    icon: 'Shield',
    sortOrder: 5,
    isBuiltin: false,
    createdAt: '2026-01-20T10:05:00Z',
    parentId: 'tag-devops',
    autoRules: 'incident\ntimeout\nreconnect\nrollback',
  },
  {
    id: 'tag-search',
    name: 'Search',
    color: '#a855f7',
    icon: 'Search',
    sortOrder: 6,
    isBuiltin: false,
    createdAt: '2026-01-20T10:06:00Z',
    parentId: 'tag-ai',
    autoRules: 'search\nretrieval\nRAG\nranking',
  },
  {
    id: 'tag-release',
    name: 'Release',
    color: '#10b981',
    icon: 'Rocket',
    sortOrder: 7,
    isBuiltin: false,
    createdAt: '2026-01-20T10:07:00Z',
    autoRules: 'release\ndeployment\npipeline',
  },
]

export const DEMO_SESSION_TAGS: SessionTag[] = [
  { sessionId: 'demo-001', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-03T11:43:00Z' },
  { sessionId: 'demo-001', tagId: 'tag-performance', position: 1, assignedAt: '2026-02-03T11:44:00Z' },
  { sessionId: 'demo-002', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-04T10:21:00Z' },
  { sessionId: 'demo-002', tagId: 'tag-performance', position: 1, assignedAt: '2026-02-04T10:22:00Z' },
  { sessionId: 'demo-003', tagId: 'tag-performance', position: 0, assignedAt: '2026-02-06T09:13:00Z' },
  { sessionId: 'demo-003', tagId: 'tag-backend', position: 1, assignedAt: '2026-02-06T09:14:00Z' },
  { sessionId: 'demo-004', tagId: 'tag-frontend', position: 0, assignedAt: '2026-02-08T06:49:00Z' },
  { sessionId: 'demo-005', tagId: 'tag-devops', position: 0, assignedAt: '2026-02-10T05:31:00Z' },
  { sessionId: 'demo-005', tagId: 'tag-reliability', position: 1, assignedAt: '2026-02-10T05:32:00Z' },
  { sessionId: 'demo-006', tagId: 'tag-ai', position: 0, assignedAt: '2026-02-12T12:06:00Z' },
  { sessionId: 'demo-006', tagId: 'tag-search', position: 1, assignedAt: '2026-02-12T12:07:00Z' },
  { sessionId: 'demo-007', tagId: 'tag-reliability', position: 0, assignedAt: '2026-02-14T12:56:00Z' },
  { sessionId: 'demo-008', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-16T08:16:00Z' },
  { sessionId: 'demo-009', tagId: 'tag-frontend', position: 0, assignedAt: '2026-02-18T09:06:00Z' },
  { sessionId: 'demo-010', tagId: 'tag-devops', position: 0, assignedAt: '2026-02-20T04:41:00Z' },
  { sessionId: 'demo-010', tagId: 'tag-release', position: 1, assignedAt: '2026-02-20T04:42:00Z' },
  { sessionId: 'demo-011', tagId: 'tag-ai', position: 0, assignedAt: '2026-02-23T12:46:00Z' },
  { sessionId: 'demo-011', tagId: 'tag-reliability', position: 1, assignedAt: '2026-02-23T12:47:00Z' },
  { sessionId: 'demo-012', tagId: 'tag-release', position: 0, assignedAt: '2026-02-26T13:19:00Z' },
  { sessionId: 'demo-012', tagId: 'tag-search', position: 1, assignedAt: '2026-02-26T13:20:00Z' },
  { sessionId: 'demo-013', tagId: 'tag-backend', position: 0, assignedAt: '2026-02-28T12:01:00Z' },
  { sessionId: 'demo-014', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-01T08:33:00Z' },
  { sessionId: 'demo-015', tagId: 'tag-devops', position: 0, assignedAt: '2026-03-02T04:21:00Z' },
  { sessionId: 'demo-016', tagId: 'tag-search', position: 0, assignedAt: '2026-03-03T09:56:00Z' },
  { sessionId: 'demo-017', tagId: 'tag-devops', position: 0, assignedAt: '2026-03-03T11:29:00Z' },
  { sessionId: 'demo-017', tagId: 'tag-release', position: 1, assignedAt: '2026-03-03T11:30:00Z' },
  { sessionId: 'demo-018', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-03T12:27:00Z' },
  { sessionId: 'demo-018', tagId: 'tag-search', position: 1, assignedAt: '2026-03-03T12:28:00Z' },
  { sessionId: 'demo-019', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-03T13:13:00Z' },
  { sessionId: 'demo-019', tagId: 'tag-release', position: 1, assignedAt: '2026-03-03T13:14:00Z' },
  { sessionId: 'demo-020', tagId: 'tag-backend', position: 0, assignedAt: '2026-03-03T14:11:00Z' },
  { sessionId: 'demo-020', tagId: 'tag-frontend', position: 1, assignedAt: '2026-03-03T14:12:00Z' },
  { sessionId: 'demo-021', tagId: 'tag-devops', position: 0, assignedAt: '2026-03-04T05:05:00Z' },
  { sessionId: 'demo-021', tagId: 'tag-reliability', position: 1, assignedAt: '2026-03-04T05:06:00Z' },
  { sessionId: 'demo-022', tagId: 'tag-backend', position: 0, assignedAt: '2026-03-04T09:19:00Z' },
  { sessionId: 'demo-022', tagId: 'tag-release', position: 1, assignedAt: '2026-03-04T09:20:00Z' },
  { sessionId: 'demo-023', tagId: 'tag-frontend', position: 0, assignedAt: '2026-03-04T12:53:00Z' },
  { sessionId: 'demo-023', tagId: 'tag-performance', position: 1, assignedAt: '2026-03-04T12:54:00Z' },
  { sessionId: 'demo-024', tagId: 'tag-release', position: 0, assignedAt: '2026-03-05T04:47:00Z' },
  { sessionId: 'demo-024', tagId: 'tag-search', position: 1, assignedAt: '2026-03-05T04:48:00Z' },
]

export const DEMO_FAVORITES: FavoriteItem[] = [
  {
    id: 'demo-001',
    type: 'session',
    name: 'Checkout Risk Rule Alignment',
    path: '/demo/commerce/session-001.jsonl',
    addedAt: '2026-02-03T11:45:00Z',
  },
  {
    id: 'demo-006',
    type: 'session',
    name: 'RAG Recall Quality Regression',
    path: '/demo/ai/session-006.jsonl',
    addedAt: '2026-02-12T12:08:00Z',
  },
  {
    id: 'demo-012',
    type: 'session',
    name: 'Demo Mode Coverage Expansion',
    path: '/demo/pi-manager/session-012.jsonl',
    addedAt: '2026-02-26T13:21:00Z',
  },
  {
    id: 'demo-024',
    type: 'session',
    name: 'Offline Demo Bundle Packaging',
    path: '/demo/pi-manager/session-024.jsonl',
    addedAt: '2026-03-05T04:49:00Z',
  },
  {
    id: 'fav-project-commerce',
    type: 'project',
    name: 'commerce-platform',
    path: '/Users/demo/commerce-platform',
    addedAt: '2026-02-18T09:10:00Z',
  },
  {
    id: 'fav-project-psm',
    type: 'project',
    name: 'pi-session-manager',
    path: '/Users/demo/pi-session-manager',
    addedAt: '2026-03-05T04:50:00Z',
  },
]
