// Automatically generated by download_themes.mjs
export interface CodexThemeTheme {
  accent: string;
  background: string;
  foreground: string;
  surface: string;
  contrast: number;
  opaqueWindows: boolean;
  semanticColors?: {
    diffAdded?: string;
    diffRemoved?: string;
    skill?: string;
    success?: string;
    warning?: string;
    error?: string;
    [key: string]: string | undefined;
  };
  fonts?: {
    ui?: string;
    code?: string;
  };
}

export interface CodexTheme {
  name: string;
  slug: string;
  author: string;
  type: string;
  mode: 'dark' | 'light';
  tags: string[];
  description: string;
  codeThemeId?: string;
  theme: CodexThemeTheme;
}

export const BUILT_IN_CODEX_THEMES: CodexTheme[] = [
  {
    "name": "Absolutely Light",
    "slug": "absolutely-light",
    "author": "OpenAI / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "neutral",
      "default"
    ],
    "description": "Absolutely Light adapted for Codex App with warm neutrals and soft contrast.",
    "codeThemeId": "absolutely",
    "theme": {
      "accent": "#cc7d5e",
      "background": "#f9f9f7",
      "foreground": "#2d2d2b",
      "surface": "#ffffff",
      "contrast": 45,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#2f9e44",
        "diffRemoved": "#e03131",
        "skill": "#a75d44"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Ayu Dark",
    "slug": "ayu-dark",
    "author": "teabyii / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "warm",
      "ayu"
    ],
    "description": "Ayu Dark adapted for Codex App with warm highlights and soft contrast.",
    "codeThemeId": "ayu",
    "theme": {
      "accent": "#ffb454",
      "background": "#0f1419",
      "foreground": "#e6e1cf",
      "surface": "#171b24",
      "contrast": 47,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#7fd962",
        "diffRemoved": "#f26d78",
        "skill": "#d2a6ff"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Ayu Light",
    "slug": "ayu-light",
    "author": "teabyii / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "warm",
      "ayu"
    ],
    "description": "Ayu Light adapted for Codex App with warm orange highlights and clean contrast.",
    "codeThemeId": "ayu",
    "theme": {
      "accent": "#f29718",
      "background": "#fcfcfc",
      "foreground": "#5c6166",
      "surface": "#ffffff",
      "contrast": 20,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#6cbf43",
        "diffRemoved": "#f07171",
        "skill": "#399ee6"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Catppuccin Latte",
    "slug": "catppuccin-latte",
    "author": "Catppuccin / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "pastel",
      "latte"
    ],
    "description": "Catppuccin Latte adapted for Codex App with soft pastel accents and low glare.",
    "codeThemeId": "catppuccin",
    "theme": {
      "accent": "#1e66f5",
      "background": "#eff1f5",
      "foreground": "#4c4f69",
      "surface": "#e6e9ef",
      "contrast": 22,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#40a02b",
        "diffRemoved": "#d20f39",
        "skill": "#8839ef"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Catppuccin Mocha",
    "slug": "catppuccin-mocha",
    "author": "Catppuccin / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "pastel",
      "mocha"
    ],
    "description": "Catppuccin Mocha adapted for Codex App with pastel accents and soft contrast.",
    "codeThemeId": "catppuccin",
    "theme": {
      "accent": "#89b4fa",
      "background": "#1e1e2e",
      "foreground": "#cdd6f4",
      "surface": "#313244",
      "contrast": 46,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#a6e3a1",
        "diffRemoved": "#f38ba8",
        "skill": "#cba6f7"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Codex Dark",
    "slug": "codex-dark",
    "author": "OpenAI / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "default",
      "codex"
    ],
    "description": "Codex Dark adapted from the built-in Codex look with a bright blue accent.",
    "codeThemeId": "codex",
    "theme": {
      "accent": "#339cff",
      "background": "#181818",
      "foreground": "#ffffff",
      "surface": "#2d2d2b",
      "contrast": 45,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#34c759",
        "diffRemoved": "#ff5f57",
        "skill": "#7c8cff"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Dracula",
    "slug": "dracula",
    "author": "Dracula Theme / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "purple",
      "neon"
    ],
    "description": "Dracula adapted for Codex App with vivid purple accents and high contrast.",
    "codeThemeId": "dracula",
    "theme": {
      "accent": "#bd93f9",
      "background": "#282a36",
      "foreground": "#f8f8f2",
      "surface": "#44475a",
      "contrast": 55,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#50fa7b",
        "diffRemoved": "#ff5555",
        "skill": "#bd93f9"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Everforest Dark",
    "slug": "everforest-dark",
    "author": "sainnhe / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "forest",
      "muted"
    ],
    "description": "Everforest Dark adapted for Codex App with natural greens and low eye strain.",
    "codeThemeId": "everforest",
    "theme": {
      "accent": "#a7c080",
      "background": "#2b3339",
      "foreground": "#d3c6aa",
      "surface": "#374145",
      "contrast": 44,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#a7c080",
        "diffRemoved": "#e67e80",
        "skill": "#d699b6"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Everforest Light",
    "slug": "everforest-light",
    "author": "sainnhe / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "forest",
      "muted"
    ],
    "description": "Everforest Light adapted for Codex App with muted greens and warm paper tones.",
    "codeThemeId": "everforest",
    "theme": {
      "accent": "#93b259",
      "background": "#fdf6e3",
      "foreground": "#5c6a72",
      "surface": "#f4f0d9",
      "contrast": 26,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#8da101",
        "diffRemoved": "#f85552",
        "skill": "#df69ba"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "GitHub Dark",
    "slug": "github-dark",
    "author": "GitHub / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "github",
      "clean"
    ],
    "description": "GitHub Dark adapted for Codex App with a clean blue accent and neutral surfaces.",
    "codeThemeId": "github",
    "theme": {
      "accent": "#58a6ff",
      "background": "#0d1117",
      "foreground": "#c9d1d9",
      "surface": "#161b22",
      "contrast": 40,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#3fb950",
        "diffRemoved": "#f85149",
        "skill": "#a371f7"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "GitHub Light",
    "slug": "github-light",
    "author": "GitHub / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "clean",
      "github"
    ],
    "description": "GitHub Light adapted for Codex App with a clean neutral palette.",
    "codeThemeId": "github-light",
    "theme": {
      "accent": "#0969da",
      "background": "#ffffff",
      "foreground": "#1f2328",
      "surface": "#f6f8fa",
      "contrast": 18,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#1a7f37",
        "diffRemoved": "#cf222e",
        "skill": "#8250df"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Gruvbox Dark",
    "slug": "gruvbox-dark",
    "author": "morhetz / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "warm",
      "retro"
    ],
    "description": "Gruvbox Dark adapted for Codex App with warm contrast and earthy tones.",
    "codeThemeId": "gruvbox",
    "theme": {
      "accent": "#d79921",
      "background": "#282828",
      "foreground": "#ebdbb2",
      "surface": "#3c3836",
      "contrast": 61,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#98971a",
        "diffRemoved": "#cc241d",
        "skill": "#b16286"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Gruvbox Light",
    "slug": "gruvbox-light",
    "author": "morhetz / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "warm",
      "retro"
    ],
    "description": "Gruvbox Light adapted for Codex App with warm paper tones and strong contrast.",
    "codeThemeId": "gruvbox",
    "theme": {
      "accent": "#d79921",
      "background": "#fbf1c7",
      "foreground": "#3c3836",
      "surface": "#ebdbb2",
      "contrast": 34,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#98971a",
        "diffRemoved": "#cc241d",
        "skill": "#b16286"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Material Lighter",
    "slug": "material-lighter",
    "author": "material-theme / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "material",
      "clean"
    ],
    "description": "Material Lighter adapted for Codex App with crisp surfaces and vivid purple accents.",
    "codeThemeId": "material",
    "theme": {
      "accent": "#7c4dff",
      "background": "#fafafa",
      "foreground": "#546e7a",
      "surface": "#ffffff",
      "contrast": 18,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#91b859",
        "diffRemoved": "#ff5370",
        "skill": "#c792ea"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Material Ocean",
    "slug": "material-ocean",
    "author": "material-theme / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "material",
      "ocean"
    ],
    "description": "Material Ocean adapted for Codex App with cool blues and vibrant syntax accents.",
    "codeThemeId": "material",
    "theme": {
      "accent": "#82aaff",
      "background": "#263238",
      "foreground": "#eeffff",
      "surface": "#2e3c43",
      "contrast": 46,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#c3e88d",
        "diffRemoved": "#f07178",
        "skill": "#c792ea"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Monokai",
    "slug": "monokai",
    "author": "Wimer Hazenberg / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "classic",
      "monokai"
    ],
    "description": "Monokai adapted for Codex App with bold contrast and saturated highlights.",
    "codeThemeId": "monokai",
    "theme": {
      "accent": "#fd971f",
      "background": "#272822",
      "foreground": "#f8f8f2",
      "surface": "#3e3d32",
      "contrast": 56,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#a6e22e",
        "diffRemoved": "#f92672",
        "skill": "#ae81ff"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Night Owl",
    "slug": "night-owl",
    "author": "Sarah Drasner / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "owl",
      "blue"
    ],
    "description": "Night Owl adapted for Codex App with deep navy surfaces and luminous highlights.",
    "codeThemeId": "night-owl",
    "theme": {
      "accent": "#82aaff",
      "background": "#011627",
      "foreground": "#d6deeb",
      "surface": "#1d3b53",
      "contrast": 48,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#22da6e",
        "diffRemoved": "#ef5350",
        "skill": "#c792ea"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Nord",
    "slug": "nord",
    "author": "arcticicestudio / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "arctic",
      "calm"
    ],
    "description": "Nord adapted for Codex App with cool blue accents and balanced contrast.",
    "codeThemeId": "nord",
    "theme": {
      "accent": "#88c0d0",
      "background": "#2e3440",
      "foreground": "#eceff4",
      "surface": "#3b4252",
      "contrast": 43,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#a3be8c",
        "diffRemoved": "#bf616a",
        "skill": "#b48ead"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "One Dark",
    "slug": "one-dark",
    "author": "Atom / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "modern",
      "balanced"
    ],
    "description": "One Dark adapted for Codex App with the classic Atom-style palette.",
    "codeThemeId": "one-dark",
    "theme": {
      "accent": "#61afef",
      "background": "#282c34",
      "foreground": "#abb2bf",
      "surface": "#353b45",
      "contrast": 41,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#98c379",
        "diffRemoved": "#e06c75",
        "skill": "#c678dd"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Poimandres",
    "slug": "poimandres",
    "author": "poimandres / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "poimandres",
      "soft"
    ],
    "description": "Poimandres adapted for Codex App with airy highlights and low-glare surfaces.",
    "codeThemeId": "poimandres",
    "theme": {
      "accent": "#add7ff",
      "background": "#1b1e28",
      "foreground": "#e4f0fb",
      "surface": "#303340",
      "contrast": 45,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#5de4c7",
        "diffRemoved": "#d0679d",
        "skill": "#fae4fc"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Rosé Pine",
    "slug": "rose-pine",
    "author": "rose-pine / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "rose-pine",
      "soft"
    ],
    "description": "Rosé Pine adapted for Codex App with soft mauves and subdued contrast.",
    "codeThemeId": "rose-pine",
    "theme": {
      "accent": "#c4a7e7",
      "background": "#191724",
      "foreground": "#e0def4",
      "surface": "#26233a",
      "contrast": 44,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#9ccfd8",
        "diffRemoved": "#eb6f92",
        "skill": "#c4a7e7"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Rosé Pine Dawn",
    "slug": "rose-pine-dawn",
    "author": "rose-pine / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "rose-pine",
      "soft"
    ],
    "description": "Rosé Pine Dawn adapted for Codex App with warm cream surfaces and muted mauves.",
    "codeThemeId": "rose-pine",
    "theme": {
      "accent": "#d7827e",
      "background": "#faf4ed",
      "foreground": "#575279",
      "surface": "#fffaf3",
      "contrast": 18,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#56949f",
        "diffRemoved": "#b4637a",
        "skill": "#907aa9"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Solarized Dark",
    "slug": "solarized-dark",
    "author": "Ethan Schoonover / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "classic",
      "solarized"
    ],
    "description": "Solarized Dark adapted for Codex App with balanced blue accents and restrained contrast.",
    "codeThemeId": "solarized",
    "theme": {
      "accent": "#268bd2",
      "background": "#002b36",
      "foreground": "#839496",
      "surface": "#073642",
      "contrast": 36,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#859900",
        "diffRemoved": "#dc322f",
        "skill": "#6c71c4"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Solarized Light",
    "slug": "solarized-light",
    "author": "Ethan Schoonover / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "classic",
      "muted"
    ],
    "description": "Solarized Light adapted for Codex App with warm neutrals and restrained contrast.",
    "codeThemeId": "solarized",
    "theme": {
      "accent": "#268bd2",
      "background": "#fdf6e3",
      "foreground": "#586e75",
      "surface": "#eee8d5",
      "contrast": 22,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#859900",
        "diffRemoved": "#dc322f",
        "skill": "#6c71c4"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Tokyo Day",
    "slug": "tokyo-day",
    "author": "enkia / Codex Themes",
    "type": "app",
    "mode": "light",
    "tags": [
      "light",
      "blue",
      "popular"
    ],
    "description": "Tokyo Day adapted for Codex App with cool blues and a soft cloudy background.",
    "codeThemeId": "tokyo-night",
    "theme": {
      "accent": "#2959aa",
      "background": "#e6e7ed",
      "foreground": "#343b59",
      "surface": "#dfe1e8",
      "contrast": 24,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#587539",
        "diffRemoved": "#8c4351",
        "skill": "#5a4a78"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  },
  {
    "name": "Tokyo Night",
    "slug": "tokyo-night",
    "author": "enkia / Codex Themes",
    "type": "app",
    "mode": "dark",
    "tags": [
      "dark",
      "blue",
      "popular"
    ],
    "description": "Tokyo Night adapted for Codex App with a soft blue accent.",
    "codeThemeId": "tokyo-night",
    "theme": {
      "accent": "#7aa2f7",
      "background": "#1a1b26",
      "foreground": "#c0caf5",
      "surface": "#24283b",
      "contrast": 52,
      "opaqueWindows": false,
      "semanticColors": {
        "diffAdded": "#9ece6a",
        "diffRemoved": "#f7768e",
        "skill": "#bb9af7"
      },
      "fonts": {
        "ui": "SF Pro Text",
        "code": "SF Mono"
      }
    }
  }
];
