const STYLE_ID = 'psm-session-graph-styles'

export function ensureSessionGraphStyles() {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = `
.psm-graph-shell{display:grid;grid-template-columns:minmax(0,1fr) 320px;width:100%;height:100%;overflow:hidden;background:rgb(var(--color-background));}
.psm-graph-canvas{position:relative;min-width:0;min-height:0;overflow:hidden;}.psm-graph-canvas>.react-flow{width:100%;height:100%;}
.psm-graph-inspector{position:relative;z-index:10;min-width:0;overflow:auto;padding:12px;border-left:1px solid rgba(var(--color-border),.72);background:rgba(var(--color-surface-dark),.82);backdrop-filter:blur(12px);color:rgb(var(--color-muted-foreground));font-size:11px;box-shadow:inset 1px 0 0 rgba(var(--highlight-rgb),.04)}
.psm-graph-inspector-title{display:flex;align-items:center;gap:7px;color:rgb(var(--color-foreground));font-weight:650}.psm-graph-stats{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px;font:10px var(--font-family-mono,ui-monospace,Menlo,monospace)}.psm-graph-stats span,.psm-graph-kind{border:1px solid rgba(var(--accent-rgb),.14);border-radius:5px;padding:1px 5px;background:rgba(var(--color-background),.28)}
.psm-graph-active{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:6px;align-items:center;margin-top:8px}.psm-graph-active-text{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:rgb(var(--color-foreground))}.psm-graph-jsonl-inspector{display:grid;gap:5px;margin-top:10px;font:10px var(--font-family-mono,ui-monospace,Menlo,monospace)}.psm-graph-jsonl-inspector div{display:grid;grid-template-columns:58px minmax(0,1fr);gap:6px;align-items:start}.psm-graph-jsonl-inspector span{color:rgb(var(--color-muted-foreground))}.psm-graph-jsonl-inspector code{min-width:0;overflow-wrap:anywhere;color:rgb(var(--color-foreground))}
.psm-graph-toolbar{position:absolute;top:10px;right:10px;z-index:10;display:flex;gap:2px;padding:3px;border:1px solid rgba(var(--color-border),.72);border-radius:8px;background:rgba(var(--color-surface-dark),.9);backdrop-filter:blur(12px);box-shadow:0 10px 28px rgba(var(--shadow-rgb),.14)}.psm-graph-toolbar button{display:flex;align-items:center;justify-content:center;width:29px;height:29px;border:0;border-radius:6px;background:transparent;color:rgb(var(--color-muted-foreground))}.psm-graph-toolbar button:hover{background:rgba(var(--color-background),.55);color:rgb(var(--color-foreground))}
.psm-graph-searchbar{position:absolute;top:55px;right:10px;z-index:10;display:flex;align-items:center;gap:5px;width:min(360px,calc(100% - 24px));padding:4px 6px;border:1px solid rgba(var(--color-border),.62);border-radius:8px;background:rgba(var(--color-surface-dark),.88);backdrop-filter:blur(12px);box-shadow:0 10px 28px rgba(var(--shadow-rgb),.12);color:rgb(var(--color-muted-foreground))}.psm-graph-searchbar input{min-width:0;flex:1;border:0;background:transparent;color:rgb(var(--color-foreground));font-size:12px;outline:0}.psm-graph-searchbar button{height:22px;border:0;border-radius:5px;background:rgba(var(--color-background),.35);padding:0 6px;color:rgb(var(--color-muted-foreground))}.psm-graph-searchbar button:disabled{opacity:.35}.psm-graph-searchbar span{font:10px var(--font-family-mono,ui-monospace,Menlo,monospace)}
.psm-graph-filterbar{position:absolute;top:92px;right:10px;z-index:10;display:flex;max-width:min(720px,calc(100% - 24px));gap:2px;padding:3px;border:1px solid rgba(var(--color-border),.62);border-radius:8px;background:rgba(var(--color-surface-dark),.86);backdrop-filter:blur(12px);box-shadow:0 10px 28px rgba(var(--shadow-rgb),.12)}.psm-graph-filterbar button{height:25px;border:0;border-radius:6px;background:transparent;padding:0 8px;color:rgb(var(--color-muted-foreground));font-size:11px}.psm-graph-filterbar button:hover,.psm-graph-filterbar button.active{background:rgba(var(--color-background),.58);color:rgb(var(--color-foreground))}
.psm-graph-legend{position:absolute;left:10px;bottom:10px;z-index:10;display:flex;flex-wrap:wrap;gap:7px;max-width:calc(100% - 170px);padding:6px 8px;border:1px solid rgba(var(--color-border),.58);border-radius:8px;background:rgba(var(--color-surface-dark),.78);backdrop-filter:blur(12px);color:rgb(var(--color-muted-foreground));font:10px var(--font-family-mono,ui-monospace,Menlo,monospace)}.psm-graph-legend span{display:inline-flex;align-items:center;gap:4px}.psm-graph-dot{width:7px;height:7px;border-radius:999px;background:rgb(var(--color-muted-foreground))}.psm-graph-dot-user{background:var(--borderAccent,var(--accent))}.psm-graph-dot-assistant{background:rgb(var(--color-foreground))}.psm-graph-dot-toolResult{background:var(--toolTitle,var(--accent))}.psm-graph-dot-label{background:rgb(var(--color-cyan))}.psm-graph-dot-branch{background:rgb(var(--color-purple))}.psm-graph-dot-meta{background:rgb(var(--color-muted-foreground))}
.psm-graph-node{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:start;column-gap:8px;padding:8px 9px;overflow:hidden;border:1.5px solid rgb(var(--color-border));border-radius:7px;background:rgb(var(--color-card));color:rgb(var(--color-muted-foreground));font-size:11px;line-height:1.25;box-shadow:0 1px 2px rgba(var(--shadow-rgb),.12)}.psm-graph-node-user{background:var(--userMessageBg,rgba(86,156,214,.12));border-color:var(--borderAccent,rgb(86,156,214));color:var(--userMessageText,var(--accent))}.psm-graph-node-assistant{background:rgb(var(--color-card));border-color:rgb(var(--color-border));color:rgb(var(--color-foreground))}.psm-graph-node-toolResult{background:var(--toolPendingBg,rgba(126,231,135,.12));border-color:var(--toolTitle,var(--accent));color:var(--toolTitle,var(--accent))}.psm-graph-node-system,.psm-graph-node-developer{background:rgba(var(--color-surface-dark),.72);border-color:rgb(var(--color-border));color:rgb(var(--color-muted-foreground))}.psm-graph-node-session{background:rgba(var(--accent-rgb),.1);border-color:var(--accent);color:var(--accent)}.psm-graph-node-label{background:rgba(var(--color-cyan),.1);border-color:rgb(var(--color-cyan));color:rgb(var(--color-cyan))}.psm-graph-node-model,.psm-graph-node-thinking{background:rgba(var(--color-blue),.1);border-color:rgb(var(--color-blue));color:rgb(var(--color-blue))}.psm-graph-node-branch{background:rgba(var(--color-purple),.12);border-color:rgb(var(--color-purple));color:rgb(var(--color-purple))}.psm-graph-node-meta{background:var(--customMessageBg,rgba(255,166,87,.12));border-color:var(--customMessageLabel,rgb(255,166,87));color:var(--customMessageLabel,rgb(255,166,87))}.psm-graph-node-active{border-color:var(--accent)!important;box-shadow:0 0 0 1px var(--accent)}.psm-graph-node-path:not(.psm-graph-node-active){border-color:var(--selectedBg,var(--accent))!important}.psm-graph-node-icon{margin-top:1px}.psm-graph-node-main{min-width:0;display:flex;flex-direction:column;gap:3px}.psm-graph-node-topline{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;align-items:center}.psm-graph-node-label,.psm-graph-node-kind,.psm-graph-node-preview{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.psm-graph-node-label{color:rgb(var(--color-foreground));font-weight:620}.psm-graph-node-preview{display:block;color:rgb(var(--color-muted-foreground));font-size:10px}.psm-graph-node-kind{font:9px var(--font-family-mono,ui-monospace,Menlo,monospace);color:rgb(var(--color-muted-foreground))}.psm-graph-node-badge{max-width:76px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:1px solid rgba(var(--color-border),.7);border-radius:4px;padding:1px 4px;background:rgba(var(--color-background),.38);font:9px var(--font-family-mono,ui-monospace,Menlo,monospace);color:rgb(var(--color-muted-foreground))}.psm-graph-skip{padding:1px 4px;border:1px solid rgba(var(--accent-rgb),.16);border-radius:4px;font-size:9px;opacity:.78}
.psm-graph-edge .react-flow__edge-path{stroke:rgb(var(--color-border));stroke-width:1}.psm-graph-edge-active .react-flow__edge-path{stroke:var(--accent);stroke-width:2}.psm-graph-shell .react-flow__background{background:rgb(var(--color-background))!important}.psm-graph-shell .react-flow__minimap{border:1px solid rgb(var(--color-border));border-radius:8px;background:rgb(var(--color-card))!important;box-shadow:0 8px 18px rgba(var(--shadow-rgb),.18)}
@media (max-width: 760px){.psm-graph-shell{grid-template-columns:1fr;grid-template-rows:minmax(0,1fr) minmax(180px,34dvh)}.psm-graph-inspector{border-left:0;border-top:1px solid rgba(var(--color-border),.72)}.psm-graph-filterbar{left:10px;right:10px;max-width:none;overflow-x:auto}.psm-graph-searchbar{left:10px;right:10px;width:auto}.psm-graph-legend{display:none}}
`
  document.head.appendChild(style)
}
