import type { PsmPluginManifest } from '@pi-session-manager/plugin-sdk'

export const manifest: PsmPluginManifest = {
  manifestVersion: 1,
  id: 'builtin.semantic-search',
  name: 'Semantic Search',
  version: '0.1.0',
  runtime: {
    sdk: '^0.1.0',
    host: '>=0.6.3',
  },
  permissions: ['agent:invoke', 'sessions:read', 'search:read', 'model:invoke'],
  configuration: {
    properties: [
      {
        key: 'defaultScope',
        type: 'select',
        title: 'Default Search Scope',
        description: 'Default scope for semantic search',
        options: [
          { value: 'project', label: 'Current Project' },
          { value: 'global', label: 'All Projects' },
        ],
        default: 'project',
      },
      {
        key: 'maxResults',
        type: 'number',
        title: 'Max Results',
        description: 'Maximum number of search results to display',
        default: 20,
      },
      {
        key: 'enableAiExpansion',
        type: 'boolean',
        title: 'AI Query Expansion',
        description: 'Use AI to expand search queries with synonyms and related terms',
        default: true,
      },
      {
        key: 'provider',
        type: 'model-provider',
        title: 'Agent Model Provider',
        description: 'Provider used by the semantic search agent. Leave empty to use the host default.',
        modelKey: 'model',
        default: '',
      },
      {
        key: 'model',
        type: 'model-id',
        title: 'Agent Model',
        description: 'Model used by the semantic search agent. Leave empty to use the host default.',
        providerKey: 'provider',
        default: '',
      },
    ],
  },
  i18n: {
    'en-US': {
      plugins: {
        semanticSearch: {
          title: 'Semantic Search',
          searchPlaceholder: 'Search sessions by meaning...',
          scopeProject: 'This Project',
          scopeGlobal: 'All Projects',
          noResults: 'No results found',
          searching: 'Searching...',
          aiExpanding: 'Expanding query...',
          sessionName: 'Session',
          project: 'Project',
          matchSnippet: 'Match',
          score: 'Relevance',
          openSession: 'Open Session',
          filters: 'Filters',
          roleFilter: 'Role',
          roleAll: 'All',
          roleUser: 'User',
          roleAssistant: 'Assistant',
          timeRange: 'Time Range',
          timeAny: 'Any Time',
          time24h: 'Last 24 Hours',
          time7d: 'Last 7 Days',
          time30d: 'Last 30 Days',
        },
      },
    },
    'zh-CN': {
      plugins: {
        semanticSearch: {
          title: '语义搜索',
          searchPlaceholder: '按语义搜索会话...',
          scopeProject: '当前项目',
          scopeGlobal: '所有项目',
          noResults: '未找到结果',
          searching: '搜索中...',
          aiExpanding: '扩展查询中...',
          sessionName: '会话',
          project: '项目',
          matchSnippet: '匹配',
          score: '相关度',
          openSession: '打开会话',
          filters: '筛选',
          roleFilter: '角色',
          roleAll: '全部',
          roleUser: '用户',
          roleAssistant: '助手',
          timeRange: '时间范围',
          timeAny: '任意时间',
          time24h: '最近24小时',
          time7d: '最近7天',
          time30d: '最近30天',
        },
      },
    },
    'ja-JP': {
      plugins: {
        semanticSearch: {
          title: 'セマンティック検索',
          searchPlaceholder: '意味でセッションを検索...',
          scopeProject: 'このプロジェクト',
          scopeGlobal: '全プロジェクト',
          noResults: '結果が見つかりません',
          searching: '検索中...',
          aiExpanding: 'クエリを展開中...',
          sessionName: 'セッション',
          project: 'プロジェクト',
          matchSnippet: 'マッチ',
          score: '関連度',
          openSession: 'セッションを開く',
          filters: 'フィルター',
          roleFilter: 'ロール',
          roleAll: 'すべて',
          roleUser: 'ユーザー',
          roleAssistant: 'アシスタント',
          timeRange: '時間範囲',
          timeAny: 'いつでも',
          time24h: '過去24時間',
          time7d: '過去7日',
          time30d: '過去30日',
        },
      },
    },
  },
}
