import type { PsmPluginManifest } from '@pi-session-manager/plugin-sdk'

export const manifest: PsmPluginManifest = {
  manifestVersion: 1,
  id: 'builtin.kanban-board',
  name: 'Kanban Board',
  version: '0.1.0',
  runtime: {
    sdk: '^0.1.0',
    host: '>=0.6.3',
  },
  permissions: ['sessions:read', 'tags:read', 'tags:write', 'config:read', 'config:write'],
  i18n: {
    'en-US': {
      plugins: {
        kanbanBoard: {
          title: 'Kanban Board',
          sidebarTitle: 'Kanban Sidebar',
          allProjects: 'All Projects',
          noStatus: 'No status',
          labels: 'Labels',
          manageLabels: 'Manage labels',
          sessionColumn: {
            title: 'Kanban',
            openBoard: 'Show in Kanban board',
          },
          dropSessionsHere: 'Drop sessions here',
          newSession: 'New Session',
          newSessionShort: 'New',
          dragColumn: 'Drag column',
          columnSearch: 'Search',
          noColumnMatches: 'No matches',
          density: {
            comfortable: 'Comfortable',
            compact: 'Compact',
          },
          view: {
            board: 'Board',
            table: 'Table',
            roadmap: 'Roadmap',
          },
          bulk: {
            selected: '{{count}} selected',
            moveSelected: 'Move selected',
            moveTo: 'Move to...',
            deleteSelected: 'Delete selected',
            clearSelection: 'Clear selection',
          },
          workspace: {
            create: 'New Workspace',
            edit: 'Edit Workspace',
            name: 'Workspace Name',
            namePlaceholder: 'Enter workspace name',
            projectFilter: 'Project Filter',
            allProjects: 'All Projects',
            statusFilters: 'Status Filters',
            sourceFilters: 'Source Filters',
          },
          timeRange: {
            any: 'Any time',
            '1h': 'Last hour',
            '24h': 'Last 24 hours',
            '2d': 'Last 2 days',
            '7d': 'Last 7 days',
            '30d': 'Last 30 days',
          },
        },
      },
    },
    'zh-CN': {
      plugins: {
        kanbanBoard: {
          title: '看板',
          sidebarTitle: '看板侧栏',
          allProjects: '所有项目',
          noStatus: '无状态',
          labels: '标签',
          manageLabels: '管理标签',
          sessionColumn: {
            title: '看板',
            openBoard: '在看板中查看',
          },
          dropSessionsHere: '拖放会话到这里',
          newSession: '新建会话',
          newSessionShort: '新建',
          dragColumn: '拖拽列',
          columnSearch: '搜索',
          noColumnMatches: '无匹配',
          density: {
            comfortable: '舒适',
            compact: '紧凑',
          },
          view: {
            board: '看板',
            table: '表格',
            roadmap: '路线图',
          },
          bulk: {
            selected: '已选择 {{count}} 项',
            moveSelected: '移动已选',
            moveTo: '移动到...',
            deleteSelected: '删除已选',
            clearSelection: '清除选择',
          },
          workspace: {
            create: '新建工作区',
            edit: '编辑工作区',
            name: '工作区名称',
            namePlaceholder: '输入工作区名称',
            projectFilter: '项目过滤',
            allProjects: '所有项目',
            statusFilters: '状态筛选',
            sourceFilters: '来源筛选',
          },
          timeRange: {
            any: '任意时间',
            '1h': '最近1小时',
            '24h': '最近24小时',
            '2d': '最近2天',
            '7d': '最近7天',
            '30d': '最近30天',
          },
        },
      },
    },
    'de-DE': {
      plugins: {
        kanbanBoard: {
          title: 'Board',
          sidebarTitle: 'Board-Seitenleiste',
          allProjects: 'Alle Projekte',
          noStatus: 'Kein Status',
          labels: 'Labels',
          manageLabels: 'Labels verwalten',
          dropSessionsHere: 'Sitzungen hier ablegen',
          newSession: 'Neue Sitzung',
          newSessionShort: 'Neu',
          workspace: {
            create: 'Neuer Arbeitsbereich',
            edit: 'Arbeitsbereich bearbeiten',
            name: 'Arbeitsbereichsname',
            namePlaceholder: 'Arbeitsbereichsname eingeben',
            projectFilter: 'Projektfilter',
            allProjects: 'Alle Projekte',
            statusFilters: 'Statusfilter',
            sourceFilters: 'Quellenfilter',
          },
          timeRange: {
            any: 'Jederzeit',
            '1h': 'Letzte Stunde',
            '24h': 'Letzte 24 Stunden',
            '2d': 'Letzte 2 Tage',
            '7d': 'Letzte 7 Tage',
            '30d': 'Letzte 30 Tage',
          },
        },
      },
    },
    'fr-FR': {
      plugins: {
        kanbanBoard: {
          title: 'Tableau',
          sidebarTitle: 'Barre laterale du tableau',
          allProjects: 'Tous les projets',
          noStatus: 'Sans statut',
          labels: 'Labels',
          manageLabels: 'Gérer les labels',
          dropSessionsHere: 'Deposez les sessions ici',
          newSession: 'Nouvelle session',
          newSessionShort: 'Nouvelle',
          workspace: {
            create: 'Nouvel espace',
            edit: "Modifier l'espace",
            name: "Nom de l'espace",
            namePlaceholder: "Saisir le nom de l'espace",
            projectFilter: 'Filtre de projet',
            allProjects: 'Tous les projets',
            statusFilters: 'Filtres de statut',
            sourceFilters: 'Filtres de sources',
          },
          timeRange: {
            any: 'A tout moment',
            '1h': 'Derniere heure',
            '24h': 'Dernieres 24 heures',
            '2d': '2 derniers jours',
            '7d': '7 derniers jours',
            '30d': '30 derniers jours',
          },
        },
      },
    },
    'ja-JP': {
      plugins: {
        kanbanBoard: {
          title: 'ボード',
          sidebarTitle: 'ボードサイドバー',
          allProjects: '全プロジェクト',
          noStatus: 'ステータスなし',
          labels: 'ラベル',
          manageLabels: 'ラベルを管理',
          dropSessionsHere: 'ここにセッションをドロップ',
          newSession: '新規セッション',
          newSessionShort: '新規',
          workspace: {
            create: '新規ワークスペース',
            edit: 'ワークスペースを編集',
            name: 'ワークスペース名',
            namePlaceholder: 'ワークスペース名を入力',
            projectFilter: 'プロジェクトフィルター',
            allProjects: '全プロジェクト',
            statusFilters: 'ステータスフィルター',
            sourceFilters: 'ソースフィルター',
          },
          timeRange: {
            any: 'いつでも',
            '1h': '過去1時間',
            '24h': '過去24時間',
            '2d': '過去2日',
            '7d': '過去7日',
            '30d': '過去30日',
          },
        },
      },
    },
    'es-ES': {
      plugins: {
        kanbanBoard: {
          title: 'Tablero',
          sidebarTitle: 'Barra lateral del tablero',
          allProjects: 'Todos los proyectos',
          noStatus: 'Sin estado',
          labels: 'Etiquetas',
          manageLabels: 'Administrar etiquetas',
          dropSessionsHere: 'Suelta sesiones aqui',
          newSession: 'Nueva sesion',
          newSessionShort: 'Nueva',
          workspace: {
            create: 'Nuevo espacio',
            edit: 'Editar espacio',
            name: 'Nombre del espacio',
            namePlaceholder: 'Introduce el nombre del espacio',
            projectFilter: 'Filtro de proyecto',
            allProjects: 'Todos los proyectos',
            statusFilters: 'Filtros de estado',
            sourceFilters: 'Filtros de fuentes',
          },
          timeRange: {
            any: 'Cualquier momento',
            '1h': 'Ultima hora',
            '24h': 'Ultimas 24 horas',
            '2d': 'Ultimos 2 dias',
            '7d': 'Ultimos 7 dias',
            '30d': 'Ultimos 30 dias',
          },
        },
      },
    },
  },
}
