import type { PsmPluginManifest } from '@pi-session-manager/plugin-sdk'

export const manifest: PsmPluginManifest = {
  manifestVersion: 1,
  id: 'builtin.kanban-board',
  name: 'Kanban Board',
  version: '0.1.0',
  runtime: {
    sdk: '^0.1.0',
    host: '>=0.6.3',
  },
  permissions: ['sessions:read', 'tags:read', 'tags:write', 'config:read', 'config:write'],
  i18n: {
    'en-US': {
      plugins: {
        kanbanBoard: {
          title: 'Kanban Board',
          sidebarTitle: 'Kanban Sidebar',
          allProjects: 'All Projects',
          untagged: 'Unlabeled',
          dropSessionsHere: 'Drop sessions here',
          newSession: 'New Session',
          newSessionShort: 'New',
          workspace: {
            create: 'New Workspace',
            edit: 'Edit Workspace',
            name: 'Workspace Name',
            namePlaceholder: 'Enter workspace name',
            projectFilter: 'Project Filter',
            allProjects: 'All Projects',
            tagFilters: 'Tag Filters',
            sourceFilters: 'Source Filters',
          },
          timeRange: {
            any: 'Any time',
            '1h': 'Last hour',
            '24h': 'Last 24 hours',
            '2d': 'Last 2 days',
            '7d': 'Last 7 days',
            '30d': 'Last 30 days',
          },
        },
      },
    },
    'zh-CN': {
      plugins: {
        kanbanBoard: {
          title: '看板',
          sidebarTitle: '看板侧栏',
          allProjects: '所有项目',
          untagged: '未分类',
          dropSessionsHere: '拖放会话到这里',
          newSession: '新建会话',
          newSessionShort: '新建',
          workspace: {
            create: '新建工作区',
            edit: '编辑工作区',
            name: '工作区名称',
            namePlaceholder: '输入工作区名称',
            projectFilter: '项目过滤',
            allProjects: '所有项目',
            tagFilters: '标签筛选',
            sourceFilters: '来源筛选',
          },
          timeRange: {
            any: '任意时间',
            '1h': '最近1小时',
            '24h': '最近24小时',
            '2d': '最近2天',
            '7d': '最近7天',
            '30d': '最近30天',
          },
        },
      },
    },
    'de-DE': {
      plugins: {
        kanbanBoard: {
          title: 'Board',
          sidebarTitle: 'Board-Seitenleiste',
          allProjects: 'Alle Projekte',
          untagged: 'Ohne Label',
          dropSessionsHere: 'Sitzungen hier ablegen',
          newSession: 'Neue Sitzung',
          newSessionShort: 'Neu',
          workspace: {
            create: 'Neuer Arbeitsbereich',
            edit: 'Arbeitsbereich bearbeiten',
            name: 'Arbeitsbereichsname',
            namePlaceholder: 'Arbeitsbereichsname eingeben',
            projectFilter: 'Projektfilter',
            allProjects: 'Alle Projekte',
            tagFilters: 'Label-Filter',
            sourceFilters: 'Quellenfilter',
          },
          timeRange: {
            any: 'Jederzeit',
            '1h': 'Letzte Stunde',
            '24h': 'Letzte 24 Stunden',
            '2d': 'Letzte 2 Tage',
            '7d': 'Letzte 7 Tage',
            '30d': 'Letzte 30 Tage',
          },
        },
      },
    },
    'fr-FR': {
      plugins: {
        kanbanBoard: {
          title: 'Tableau',
          sidebarTitle: 'Barre laterale du tableau',
          allProjects: 'Tous les projets',
          untagged: 'Sans etiquette',
          dropSessionsHere: 'Deposez les sessions ici',
          newSession: 'Nouvelle session',
          newSessionShort: 'Nouvelle',
          workspace: {
            create: 'Nouvel espace',
            edit: "Modifier l'espace",
            name: "Nom de l'espace",
            namePlaceholder: "Saisir le nom de l'espace",
            projectFilter: 'Filtre de projet',
            allProjects: 'Tous les projets',
            tagFilters: "Filtres d'etiquettes",
            sourceFilters: 'Filtres de sources',
          },
          timeRange: {
            any: 'A tout moment',
            '1h': 'Derniere heure',
            '24h': 'Dernieres 24 heures',
            '2d': '2 derniers jours',
            '7d': '7 derniers jours',
            '30d': '30 derniers jours',
          },
        },
      },
    },
    'ja-JP': {
      plugins: {
        kanbanBoard: {
          title: 'ボード',
          sidebarTitle: 'ボードサイドバー',
          allProjects: '全プロジェクト',
          untagged: '未分類',
          dropSessionsHere: 'ここにセッションをドロップ',
          newSession: '新規セッション',
          newSessionShort: '新規',
          workspace: {
            create: '新規ワークスペース',
            edit: 'ワークスペースを編集',
            name: 'ワークスペース名',
            namePlaceholder: 'ワークスペース名を入力',
            projectFilter: 'プロジェクトフィルター',
            allProjects: '全プロジェクト',
            tagFilters: 'タグフィルター',
            sourceFilters: 'ソースフィルター',
          },
          timeRange: {
            any: 'いつでも',
            '1h': '過去1時間',
            '24h': '過去24時間',
            '2d': '過去2日',
            '7d': '過去7日',
            '30d': '過去30日',
          },
        },
      },
    },
    'es-ES': {
      plugins: {
        kanbanBoard: {
          title: 'Tablero',
          sidebarTitle: 'Barra lateral del tablero',
          allProjects: 'Todos los proyectos',
          untagged: 'Sin etiquetar',
          dropSessionsHere: 'Suelta sesiones aqui',
          newSession: 'Nueva sesion',
          newSessionShort: 'Nueva',
          workspace: {
            create: 'Nuevo espacio',
            edit: 'Editar espacio',
            name: 'Nombre del espacio',
            namePlaceholder: 'Introduce el nombre del espacio',
            projectFilter: 'Filtro de proyecto',
            allProjects: 'Todos los proyectos',
            tagFilters: 'Filtros de etiquetas',
            sourceFilters: 'Filtros de fuentes',
          },
          timeRange: {
            any: 'Cualquier momento',
            '1h': 'Ultima hora',
            '24h': 'Ultimas 24 horas',
            '2d': 'Ultimos 2 dias',
            '7d': 'Ultimos 7 dias',
            '30d': 'Ultimos 30 dias',
          },
        },
      },
    },
  },
}
